### ISSUE TITLE
HiDPI support

### ISSUE THREAD

**Issue by up-to-you** [epezent/implot#10]
How to achieve HiDPI scaling with Pie Charts ?

![image](https://user-images.githubusercontent.com/18654738/80956623-3e0bcf80-8e0a-11ea-86c1-a24f06157b4a.png)

Ubuntu 20.04
Resolution: 3840x2160
Scaling factor: 2

**Comment by epezent** [comment]
Can you try double the pixel size of the plots? Change 250,250 to 500,500.

I haven’t tested hi dpi yet. How well do the other demos scale?

**Comment by up-to-you** [comment]
![image](https://user-images.githubusercontent.com/18654738/80983570-59d89b00-8e35-11ea-994b-c4dbf30e89dc.png)

Thanks, ImVec pixels scaling solved Pie Charts issue.
Demo, as a whole, scaled quite nice. I didn't dig deep enough to adjust Imgui Theme values, but to achieve the result above i just changed font size to `29.0f`.

Can't say anything about units labels, if i understand right they simply follow global font size.

**Comment by epezent** [comment]
Yes, the fonts should just follow global size. Your other plots do look a bit squished compared to mine. Can you try changing all the {-1,300} plot sizes to {-1,600}? 

I think I may need to scale the incoming size request with the ImGui global scale parameter...

**Comment by up-to-you** [comment]
Oh, my bad.
Changed `{-1,300} / {-1,150}` to `{-1,600} / {-1,300}`

![image](https://user-images.githubusercontent.com/18654738/80989196-44676f00-8e3d-11ea-97ce-e8cebf38fddb.png)
![image](https://user-images.githubusercontent.com/18654738/80989246-577a3f00-8e3d-11ea-8fb1-7a86b96f418c.png)

I think the main issue in readability are X-axis units on Scatter and Line plots. Maybe to hide intermediate values on overlay, if it's possible.

**Comment by epezent** [comment]
Copy that. I'm not using a very sophisticated approach to showing/hiding labels at the moment. It should eventually be made to check for adjacent label bounding box collisions, and hide them based off of that.
