### ISSUE TITLE
Vertical text scaling

### ISSUE THREAD

**Issue by terewenko** [epezent/implot#100]
Very great library! Thanks!

There is a problem with scaling vertical text. The fix might look something like
```C++
void AddTextVertical(ImDrawList *DrawList, const char *text, ImVec2 pos, ImU32 text_color) {
    pos.x = IM_ROUND(pos.x);
    pos.y = IM_ROUND(pos.y);
    ImFont* font = GImGui->Font;
    ImGuiContext& g = *GImGui;

    IM_ASSERT(font->FontSize > 0.0f);
    const float scale = g.FontSize / font->FontSize;
    const ImFontGlyph *glyph;
    for (char c = *text++; c; c = *text++) {
        glyph = font->FindGlyph(c);
        if (!glyph)
            continue;

        DrawList->PrimReserve(6, 4);
        DrawList->PrimQuadUV(
            pos + ImVec2(glyph->Y0, -glyph->X0) * scale, pos + ImVec2(glyph->Y0, -glyph->X1) * scale,
            pos + ImVec2(glyph->Y1, -glyph->X1) * scale, pos + ImVec2(glyph->Y1, -glyph->X0) * scale,
            ImVec2(glyph->U0, glyph->V0), ImVec2(glyph->U1, glyph->V0),
            ImVec2(glyph->U1, glyph->V1), ImVec2(glyph->U0, glyph->V1), text_color);
        pos.y -= glyph->AdvanceX * scale;
    }
}
```
Thanks.

**Comment by epezent** [comment]
Can you post a picture of what is happening?

**Comment by terewenko** [comment]
The vertical text does not respond to scaling changes.
![image](https://user-images.githubusercontent.com/19333124/91045510-ab44aa00-e61f-11ea-8c0d-3f9c4c2d6f06.png)

**Comment by terewenko** [comment]
![image](https://user-images.githubusercontent.com/19333124/91048719-b9e19000-e624-11ea-8b05-1cdba0a3ae22.png)

**Comment by epezent** [comment]
Thanks, I just pushed a fix for scaling and offset:

![image](https://user-images.githubusercontent.com/29577475/91052500-29d12580-e5e7-11ea-997d-90871d88a76a.png)

![image](https://user-images.githubusercontent.com/29577475/91052608-508f5c00-e5e7-11ea-917e-15a3b5eb4746.png)
