### ISSUE TITLE
Box selection

### ISSUE THREAD

**Issue by ozlb** [epezent/implot#103]
Box selection with shift option (that i'm using  always) is not working properly anymore. It looks like there is a minimum delta X and anyhow is inconsistent with selection without shift that is working properly also for very little selections
Now...
![Selection_not_ok](https://user-images.githubusercontent.com/3250876/91579271-a9465800-e94b-11ea-8447-244957d5578a.gif)

Before was like this...
![Selection_ok](https://user-images.githubusercontent.com/3250876/91579246-a186b380-e94b-11ea-9ba7-d7e989401d35.gif)

**Comment by epezent** [comment]
Thanks. Can you see if the latest commits fix the issue for you?

**Comment by ozlb** [comment]
Actually not yet, but with following changes it will work:

- tall_enough flag generated by GetHeight() and GetWidth()

- horizontal mod. don't checks tall flag

- vertical mod. don't checks wide flag

Furthermore, i can't understand the meaning of ```if (IO.KeyMods == (gp.InputMap.HorizontalMod | gp.InputMap.VerticalMod) && big_enough) {``` since it will perform full plot area selection, so practically to keep everything as it is but it's changing zoom factors in strange way and again (i think is a little bit confusing).

So finally:
```cpp
    // render selection/query
    if (plot.Selecting) {
        ImRect select_bb(ImMin(IO.MousePos, plot.SelectStart), ImMax(IO.MousePos, plot.SelectStart));
        bool wide_enough = select_bb.GetWidth() > 2;
        bool tall_enough = select_bb.GetHeight() > 2;
        bool big_enough  = wide_enough && tall_enough;
        if (plot.Selecting && !gp.LockPlot && ImHasFlag(plot.Flags, ImPlotFlags_BoxSelect)) {
            const ImVec4 col   = GetStyleColorVec4(ImPlotCol_Selection);
            const ImU32 col_bg = ImGui::GetColorU32(col * ImVec4(1,1,1,0.25f));
            const ImU32 col_bd = ImGui::GetColorU32(col);
            if ((gp.X.Lock || IO.KeyMods == gp.InputMap.HorizontalMod) && wide_enough) {
                DrawList.AddRectFilled(ImVec2(gp.BB_Plot.Min.x, select_bb.Min.y), ImVec2(gp.BB_Plot.Max.x, select_bb.Max.y), col_bg);
                DrawList.AddRect(      ImVec2(gp.BB_Plot.Min.x, select_bb.Min.y), ImVec2(gp.BB_Plot.Max.x, select_bb.Max.y), col_bd);
            }
            else if ((any_y_locked || IO.KeyMods == gp.InputMap.VerticalMod) && tall_enough) {
                DrawList.AddRectFilled(ImVec2(select_bb.Min.x, gp.BB_Plot.Min.y), ImVec2(select_bb.Max.x, gp.BB_Plot.Max.y), col_bg);
                DrawList.AddRect(      ImVec2(select_bb.Min.x, gp.BB_Plot.Min.y), ImVec2(select_bb.Max.x, gp.BB_Plot.Max.y), col_bd);
            }
            else if (big_enough) {
                DrawList.AddRectFilled(select_bb.Min, select_bb.Max, col_bg);
                DrawList.AddRect(      select_bb.Min, select_bb.Max, col_bd);
            }
        }
    }
```

**Comment by epezent** [comment]
Thanks! Give it a try now. 

I think you had the `tall_enough` and `wide_enough` flags switched. Second, I fixed the ALT+SHIFT scenario so that no zoom occurs. It's simply handled so there is a visual indicator when the user transitions from ALT to SHIFT keys and vice versa. Obviously it has no effect.

**Comment by epezent** [comment]
Is this working as you expect?

**Comment by ozlb** [comment]
Sorry. I can’t test right now, but I’m pretty sure that it will work.
