### ISSUE TITLE
ImPlot_PushStyleVar with ImPlotStyleVar_Marker changes?

### ISSUE THREAD

**Issue by sonoro1234** [epezent/implot#108]
Hello,

Just pulled v0.5 and generated cimplot and LuaJIT-ImGui.

I have called CreateContext and then:
```Lua
if (ig.ImPlot_BeginPlot("Line Plot", "x", "f(x)", ig.ImVec2(-1,-1))) then
          ig.ImPlot_PlotLine("sin(50*x)", xs1, ys1, 1001);
          ig.ImPlot_SetNextMarkerStyle(ig.lib.ImPlotMarker_Circle);
          ig.ImPlot_PlotLine("x^2", xs2, ys2, 11);
          ig.ImPlot_EndPlot();
    end
```
this is working correctly, but with code that worked previously:

```Lua
if (ig.ImPlot_BeginPlot("Line Plot", "x", "f(x)", ig.ImVec2(-1,-1))) then
          ig.ImPlot_PlotLine("sin(50*x)", xs1, ys1, 1001);
          ig.ImPlot_PushStyleVarInt(ig.lib.ImPlotStyleVar_Marker, ig.lib.ImPlotMarker_Circle);
          ig.ImPlot_PlotLine("x^2", xs2, ys2, 11);
          ig.ImPlot_PopStyleVar(1);
          ig.ImPlot_EndPlot();
    end
```

I am getting

![implotv05](https://user-images.githubusercontent.com/1795930/91960662-7bc22b80-ed0a-11ea-8311-36e553c0f5d1.jpg)

There has been any changes that I am not aware of?

**Comment by epezent** [comment]
I literally just discovered and fixed a bug that may be related to this. Can you try the latest v0.6 in `master` and let me know what happens.

**Comment by sonoro1234** [comment]
after https://github.com/epezent/implot/commit/0fa1fb982afacb5037b05e1a5af6df2661b3baf8 it renders correctly

Can I take this as v0.6 for cimplot or better wait?

**Comment by epezent** [comment]
Yep go for it
