### ISSUE TITLE
When the mouse scrolls, how to ensure that the range of the y-axis and the range of  the x-axis remain at a fixed scale.

### ISSUE THREAD

**Issue by XMatrixXiang** [epezent/implot#111]
When the mouse scrolls, how to ensure that the r ange of the y-axis and the range of  the x-axis remain at a fixed scale.

**Comment by epezent** [comment]
It's not currently possible. Each axis will independently zoom by 10% of its own range.

We could introduce an `ImPlotFlags_Equal` that would constrain each axis to have the same units/pixel ratio. Would that solve the issue you are having?

**Comment by heyer2** [comment]
@epezent This feature would be extremely useful. Locking the aspect ratio between the x- and y-axes is a staple feature of most plotting frameworks.

**Comment by epezent** [comment]
Roger that. I'm looking into it.

**Comment by abey79** [comment]
This would be very useful to me if made available in Dear PyGUI (related issue: hoffstadt/DearPyGui#305).

**Comment by epezent** [comment]
I have this mostly working, but in the process I've made several changes to to how axes are handled in general.  So it's taking a bit longer than expected. Hope to merge soon.

**Comment by epezent** [comment]
This work has been completed and merged to master. Enabled with `ImPotFlags_Equal`. It only constrains the primary x and y axes; auxiliary y axes are ignored.

Please review and post back if you find issues. It ended up being a bit more nuanced than I anticipated, so there may be a chance I missed an edge case.

![equal1](https://user-images.githubusercontent.com/29577475/99210760-47e49700-278c-11eb-81f2-6d88b85a94dc.gif)
![euqal2](https://user-images.githubusercontent.com/29577475/99210766-4adf8780-278c-11eb-8f18-0b940f57192d.gif)

**Comment by dongqiceo** [comment]
i think his problem not this,he want x or y axis could be lock，or lock range （ scale factor?）

**Comment by dongqiceo** [comment]
> This work has been completed and merged to master. Enabled with `ImPotFlags_Equal`. It only constrains the primary x and y axes; auxiliary y axes are ignored.
> 
> Please review and post back if you find issues. It ended up being a bit more nuanced than I anticipated, so there may be a chance I missed an edge case.
> 
> ![equal1](https://user-images.githubusercontent.com/29577475/99210760-47e49700-278c-11eb-81f2-6d88b85a94dc.gif) ![euqal2](https://user-images.githubusercontent.com/29577475/99210766-4adf8780-278c-11eb-8f18-0b940f57192d.gif)

i think problem is scale factor? Enabled with ImPotFlags_Equal cant fix
