### ISSUE TITLE
cimplot ImPlotPoint getter

### ISSUE THREAD

**Issue by sonoro1234** [epezent/implot#112]
Work on templates is done in https://github.com/cimgui/cimplot/commit/8e246493066022a804dfc801b792a310fe6ec94a

There is only an issue already present before:

```C
CIMGUI_API void ImPlot_PlotLineG(const char* label_id,ImPlotPoint(*getter)(void* data,int idx),void* data,int count,int offset);
```

getter returning ImPlotPoint UDT (user defined type) is not usable from LuaJIT ffi. (just refuses to make a callback with such signature)

(and I think it is not usable from C in general: for example ImGui:GetWindowPos returning ImVec2 worked with gcc but made a crash in MSVC so it had to be reworked as https://github.com/cimgui/cimgui/blob/dbcc6d1529380ce51aa9e01a41459491b1be1fca/cimgui.h#L1880)

For being usable it should return `ImPlotPoint*`

**Comment by epezent** [comment]
Returning `ImPlotPoint*` is not viable because we don't want the user to have to keep the pointer alive. The only alternative is to use this signature as you suggested:

```cpp
void(*getter)(void* data, int idx, ImPlotPoint* out)
```

I tried to come up with a way you could wrap it on your side, but it's tedious. We could potentially change the API on our side. It would probably be better this way anyway. For now, can you tell your generator to skip these?

**Comment by sonoro1234** [comment]
> We could potentially change the API on our side. It would probably be better this way anyway. For now, can you tell your generator to skip these?

I will meanwhile skip generation for these.

**Comment by sonoro1234** [comment]
adding this `PlotLineG2` can be wrapped

```C++
ImPlotPoint *(*getter_funcX)(void* data, int idx);

ImPlotPoint Wrapper(void* data, int idx)
{
	ImPlotPoint *pp = getter_funcX(data, idx);
	return *pp;
}

void PlotLineG2(const char* label_id, ImPlotPoint *(*getter_func)(void* data, int idx), void* data, int count, int offset) {
	getter_funcX = getter_func;
	PlotLineG(label_id,Wrapper,data,count,offset);
}

```

**Comment by epezent** [comment]
I think it would be best to add this to only cimplot to avoid unnecessary additions on our side. There are already a good number of people using the G versions, so I'd rather not tamper with the current API either.

**Comment by sonoro1234** [comment]
In the case of

```C++
CIMGUI_API void ImPlot_PlotShadedG(const char* label_id, ImPlotPoint* (*getter1)(void* data, int idx), void* data1, ImPlotPoint* (*getter2)(void* data, int idx), void* data2, int count, int offset)
{
	getter_funcX = getter1;
	getter_funcX2 = getter2;
	ImPlot::PlotShadedG(label_id, Wrapper, data1, Wrapper2, data2, count, offset);
}
```
there are two getters so I must create also `Wrapper2` and `getter_funcX2 `

Perhaps you have another idea for doing something cleaner without variables `getter_funcX ` and `getter_funcX2` and functions `Wrapper` and `Wrapper2`?

**Comment by epezent** [comment]
@sonoro1234 , did you ever decide on a solution? My apologies for neglecting this.

**Comment by sonoro1234** [comment]
>  My apologies for neglecting this.

No worries

> did you ever decide on a solution?

As I only have one solution I cant "decide". In issue https://github.com/cimgui/cimplot/issues/3 I am just asking if somebody is able to find something simpler to what is done now.
As my request for help is already present in cimplot you can close this issue if you wish. (althougt there is a larger audience here!!)
