### ISSUE TITLE
Allow applying an offset per plot

### ISSUE THREAD

**Issue by bear24rw** [epezent/implot#115]
I have a large buffer which I would like to plot slices of but have each slice start at zero. Currently I copy each slice into a new buffer which I then loop over and apply the offset manually. It would be possible to avoid this copy if I could tell implot to apply an offset value.

Contrived example:
```cpp
auto slice_1 = std::span(big_buffer.data() + 0, 50);
auto slice_2 = std::span(big_buffer.data() + 50, 50);
ImPlot::SetNextPlotOffsetY(-1 * slice_1[0]);
ImPlot::PlotLine("slice_1", slice_1.data(), slice_1.size());
ImPlot::SetNextPlotOffsetY(-1 * slice_2[0]);
ImPlot::PlotLine("slice_2", slice_2.data(), slice_2.size());
```

In reality I need to offset both x and y.

**Comment by epezent** [comment]
This seems like a useful feature. I can look into it!

However, you might find the custom getter version, `PlotLineG` with a C++ lambda to be more versatile for what you are doing:

```cpp
std::vector<MyVec2> big_buffer;

auto slice_1 = std::span(big_buffer.data() + 0, 50);
auto slice_2 = std::span(big_buffer.data() + 50, 50);

auto offsetter = [](void* data, int i) { 
    auto& slice = *(std::span<MyVec2>*)data;
    return ImPlotPoint(slice[i].x - slice[0].x, slice[i].y - slice[0].y);
};

ImPlot::PlotLineG("offset", offsetter, &slice_1, slice_1.size());
ImPlot::PlotLineG("offset", offsetter, &slice_2, slice_2.size());
```

**Comment by bear24rw** [comment]
> However, you might find the custom getter version, PlotLineG with a C++ lambda to be more versatile for what you are doing

Oh great idea, thanks!

**Comment by epezent** [comment]
Closing this issue since it's not widely needed, and can be accomplished using either of the methods above.
