### ISSUE TITLE
DragLineX label ignores ImPlotAxisFlags_Time option

### ISSUE THREAD

**Issue by ozlb** [epezent/implot#119]
What about `ImHasFlag(plot.XAxis.Flags, ImPlotAxisFlags_Time)` option for `DragLineX()` and `DragPoint()` ?

**Comment by epezent** [comment]
Taken care of: https://github.com/epezent/implot/commit/28fedd01f99a3ed7c4a4a693e6704a7bf2f41622

Thank once again for catching my silly mistakes!
