### ISSUE TITLE
Annotate colors

### ISSUE THREAD

**Issue by ozlb** [epezent/implot#121]
Since I'm not able to control annoate text color, (`ImPlotCol_InlayText` looks like can be used only if given color.w == 0.0), i suggest a solution (or an optional solution) as per my QueryX implementation: rectangle color, fill color and text color.
The main cause of the request is due to `CalcTextColor()` return values: sometimes the choice is not perfect, like in the following screenshot (white text on orange background label).
Annotate label colors on DragLineX("a") vs QueryX label colors on DragLineX("b").
![Screenshot from 2020-09-21 22-30-13](https://user-images.githubusercontent.com/3250876/93820724-dbeb2400-fc5d-11ea-9a0b-35957180a4a8.png)

**Comment by bear24rw** [comment]
I've also noticed some hard to read combinations. Short of full control and "filled" flag could suffice.

**Comment by epezent** [comment]
Thanks guys! It wouldn't be too hard to expand the function arguments to include all styling options. I was just trying to keep the API simple and more utilitarian. There may also be a better text color algorithm out there. I just used the first thing I found

**Comment by ozlb** [comment]
To keep API simple like it is now, what about text color as negative of label color?

**Comment by ozlb** [comment]
I cross check the CalcTextColor() function and according to other sources i found, it’s enough to change the compare value from > 0.729 to > 0.5
I did several test with different color combinations and it looks good in every condition.

**Comment by epezent** [comment]
I added the 0.5 manually.
