### ISSUE TITLE
Annotate var args

### ISSUE THREAD

**Issue by sonoro1234** [epezent/implot#126]
In imgui this pattern is common

```C++
void ImGui::Text(const char* fmt, ...)
{
    va_list args;
    va_start(args, fmt);
    TextV(fmt, args);
    va_end(args);
}

void ImGui::TextV(const char* fmt, va_list args)
{
    ImGuiWindow* window = GetCurrentWindow();
    if (window->SkipItems)
        return;

    ImGuiContext& g = *GImGui;
    const char* text_end = g.TempBuffer + ImFormatStringV(g.TempBuffer, IM_ARRAYSIZE(g.TempBuffer), fmt, args);
    TextEx(g.TempBuffer, text_end, ImGuiTextFlags_NoWidthForLargeClippedText);
}
```

So that in cimgui TextV can be C wrapped and Text is wrapped as

```C
CIMGUI_API void igText(const char* fmt,...)
{
    va_list args;
    va_start(args, fmt);
    ImGui::TextV(fmt,args);
    va_end(args);
}
CIMGUI_API void igTextV(const char* fmt,va_list args)
{
    return ImGui::TextV(fmt,args);
}
```
To be able to programmatically wrap Annotate I would need AnnotateV (that would call AnnotateEx)
The same happens with AnnotateClamped

The reason is that this code is not legal:

```C
CIMGUI_API void igText(const char* fmt,...)
{
    ImGui::Text(fmt,...);
}
```

Other alternative (manually wrapping) whould be having AnnotateStrV and others in cimplot.cpp, the problem is that it cant be defined in cimplot.cpp because AnnotateEx is not exposed. (I cant call ImPlot::AnnotateEx)

I could make a PR with the AnnotateV versions if you wish (most automatic solution) or otherwise expose AnnotateEx

**Comment by epezent** [comment]
> I could make a PR with the AnnotateV versions if you wish

Yes, please do submit this PR

**Comment by sonoro1234** [comment]
Done

**Comment by epezent** [comment]
Merged
