### ISSUE TITLE
Rendering bug when using more than 15 PlotLines per Plot

### ISSUE THREAD

**Issue by JonasTietz** [epezent/implot#128]
Hello, 
I have an weird rendering bug when plotting lots of lines in a single Plot. 

![smaller](https://user-images.githubusercontent.com/17435797/95514533-651f8c00-09bc-11eb-8dbe-eb0d7152cc82.gif)

It seems like it happens at 15 PlotLines but only if I am zoomed out enough.

**Comment by epezent** [comment]
From the README:

> - If you experience data truncation and/or visual glitches, it is **HIGHLY** recommended that you EITHER:
     1) Handle the `ImGuiBackendFlags_RendererHasVtxOffset` flag in your renderer when using 16-bit indices (the official OpenGL3 renderer supports this) and use an ImGui version with patch [imgui@f6120f8](https://github.com/ocornut/imgui/commit/f6120f8e16eefcdb37b63974e6915a3dd35414be), OR...
     2) Enable 32-bit indices by uncommenting `#define ImDrawIdx unsigned int` in your ImGui `imconfig.h` file.

**Comment by JonasTietz** [comment]
Wow I'm dumb. 
Yes this fixed it :)
Thank you
