### ISSUE TITLE
Use "implot.h" instead of <implot.h> in Demo

### ISSUE THREAD

**Issue by Xipiryon** [epezent/implot#131]
Hi, 

When integrating ImPlot (as a git submodule) into my ImGui project, I had to add the folder repository as "Additional Include Directories", because the include path in implot_demo uses [`#include <implot_internal.h>`](https://github.com/epezent/implot/blob/master/implot_demo.cpp#L1417), which is a bit counter-intuitive knowing I just included all implot files directly in my project.

Maybe it would be better to simply use project include (`#include "implot_internal.h"`), or there is a specific reason to this ? (Also, I saw that implot.h is included this way [`#include "implot.h"`](https://github.com/epezent/implot/blob/master/implot_demo.cpp#L25))

Thanks 😄

**Comment by epezent** [comment]
Fixed! Thanks
