### ISSUE TITLE
Allow for configurable legend position

### ISSUE THREAD

**Issue by ArekSredzki** [epezent/implot#133]
Currently, I believe that ImPlot (like ImGui), only allows for the legend to be in the top-left hand corner of the plot.
It would be great to have the option to place it in one of:
- the other corners
- outside of the plotting region, either on the bottom or side

Regarding the other corners, I suppose that one could achieve that through modifying `ImPlotStyleVar_LegendPadding`, but a builtin option would be desirable.

Thanks!

**Comment by epezent** [comment]
> - the other corners

We can trivially add this, along with the 4 sides of the plot. I have two ideas:

```cpp
if (BeginPlot(...)) {
   SetLegendLocation(ImPlot_North | ImPlot_East);
   EndPlot();
}
```

or

```cpp
PushStyleVar(ImPlotStyleVar_LegendLocation, ImPlot_North | ImPlot_East)
if (BeginPlot(...)) {
   EndPlot();
}
PopStyleVar();
```

Thoughts?

> - outside of the plotting region, either on the bottom or side

This is a little more complicated because of our render order, and not knowing what will be in the legend until after the plot boundary is drawn. What might be possible is to expose a function that can be called after `EndPlot` which renders a legend to a separate frame, similar to what we do with `ShowColormapScale`:

![cmap](https://raw.githubusercontent.com/wiki/epezent/implot/screenshots3/heat.gif)

I need to think on this one...

**Comment by epezent** [comment]
I have a working prototype for legend locations in the `legend-loc` branch: https://github.com/epezent/implot/tree/legend-loc

![legend](https://user-images.githubusercontent.com/29577475/96216836-e4760800-0f46-11eb-8d70-af7a3b989885.gif)


```cpp

// Location, use individually or combined with bitwise OR, e.g. ImPlotLocation_North | ImPlotLocation_West
enum ImPlotLocation_ {
    ImPlotLocation_North = 1 << 0, // top
    ImPlotLocation_South = 1 << 1, // bottom
    ImPlotLocation_West  = 1 << 2, // left
    ImPlotLocation_East  = 1 << 3  // right
};

// Set the location of the current plot's legend.
IMPLOT_API void SetLegendLocation(ImPlotLocation location);
// Get the location of the current plot's legend.
IMPLOT_API ImPlotLocation GetLegendLocation();

```
**Usage:**
```cpp
if (ImPlot::BeginPlot("My Plot")) {
    ImPlot::SetLegendLocation(ImPlotLocation_North | ImPlotLocation_East);
    ....
    ImPlot::EndPlot();
}
```

**TODO**

- add relocation options to context menu or by right clicking legend
- investigate methods of rendering legend outside of plot bounding area as mentioned above

@ArekSredzki , what do you think of this API as opposed to the alternative of pushing/popping a StyleVar? I sort of prefer this.

**Comment by epezent** [comment]
I've added horizontal legends:

![legend](https://user-images.githubusercontent.com/29577475/96277383-cf769480-0f99-11eb-9338-3a4512c00ab8.gif)

```cpp
// Orientation
enum ImPlotOrientation_ {
    ImPlotOrientation_Horizontal, // left/right
    ImPlotOrientation_Vertical    // up/down
};

// Set the location of the current plot's legend (default = North|West, Vertical).
IMPLOT_API void SetLegendLocation(ImPlotLocation location, ImPlotOrientation orientation = ImPlotOrientation_Vertical);
```

Similarly, I also added the ability to change the location of the hovered mouse position label:

```cpp
// Set the locaton of the current plot's mouse position text (default = South|East).
IMPLOT_API void SetMousePosLocation(ImPlotLocation location);
```

I'll look at rendering the legend outside of the plot area next.

**Comment by ArekSredzki** [comment]
First off, thanks so much @epezent for your incredible response time!

I'm a big fan of the `ImPlot::SetLegendLocation` API you've proposed. Having a single call to configure this for a given plot makes more sense to me than pushing/popping as well.
Do you expect to use the same call for positioning the legend outside of the plot region?

**Comment by epezent** [comment]
The issue that I'm facing with exterior legends is that I'd have to know the legend size _before_ rendering the the plot area, which happens in `BeginPlot` before any calls to `PlotX`. I could probably make it work by having a 1-frame delay for legend rendering, but I don't really care for that solution.

I'm currently thinking that exterior legends will be separate frames/widgets, like `ShowColormapScale`. And so I may introduce a function like `ShowAltLegend(const char* title_id, const ImVec2& size, ImPlotOrientation orientation)` that can be called outside of `Begin/EndPlot`.

```cpp
if (BeginPlot("MyPlot",0,0,ImVec2(400,300),ImPlotFlags_NoLegend)) {
    PlotLine("Item 1"...);
    PlotLine("Item 2"...);
    PlotLine("Item 3"...);
    EndPlot();
}
// render on same line, to right
ImGui::SameLine();
ShowAltLegend("MyPlot",ImVec2(0,300),ImPlotOrientation_Vertical);
// render on new line, below
ShowAltLegend("MyPlot",ImVec2(400,0),ImPlotOrientation_Horizontal);
```

![image](https://user-images.githubusercontent.com/29577475/96323575-4a17d200-0fe3-11eb-9b3b-5b4ffca4e048.png)

I think you could also put the call before `BeginPlot` for left and top side, it would just be a frame behind.

Thoughts?

**Comment by ArekSredzki** [comment]
That seems like a reasonable approach to me given the complexity of doing it otherwise. My primary use case will likely be to have the legend below, which this fits well with.

Theoretically, you could even put the legend above, just that the contents would be delayed by 1 frame, right?

Also, I think you'd probably want to put the legend within the `if` body, after `EndPlot()`.

**Comment by epezent** [comment]
> Theoretically, you could even put the legend above, just that the contents would be delayed by 1 frame, right?
> 
> Also, I think you'd probably want to put the legend within the `if` body, after `EndPlot()`.

You are correct on both accounts! I think I'll give this a shot then. Hang tight.

**Comment by epezent** [comment]
Well, it took a little longer than expected, but I have a working prototype:

```cpp
// Shows an alternate legend for the plot identified by #title_id, outside of the plot frame (can be called before or after of Begin/EndPlot but must occur in the same ImGui window!).
IMPLOT_API void ShowAltLegend(const char* title_id, ImPlotOrientation orientation = ImPlotOrientation_Vertical, const ImVec2 size = ImVec2(0,0), bool interactable = true);
```

This will show an (optionally) interactable legend block for a particular plot _outside_ of the plot frame. You can call it from anywhere (so long as it's in the same ImGui window). With default arguments, it will generate a simple block like this:

![image](https://user-images.githubusercontent.com/29577475/96386538-51fd8080-1161-11eb-9eb8-b4d560e2aa5b.png)

By setting the `size` variable to match your plot frame size, and optionally pushing 0 for `ImGuiStyleVar_ItemSpacing`, you can make legends that look like they are a part of the plot frame, but outside the plot area:

![legend](https://user-images.githubusercontent.com/29577475/96386593-b587ae00-1161-11eb-807e-74fef4d4a3f3.gif)

```cpp
if (pos == Left) { ImPlot::ShowAltLegend("##Legend",ImPlotOrientation_Vertical,ImVec2(0,300));  ImGui::SameLine(); }
if (pos == Top)  { ImPlot::ShowAltLegend("##Legend",ImPlotOrientation_Horizontal,ImVec2(500,0));                   }
if (ImPlot::BeginPlot("##Legend","x","y",ImVec2(500,300),ImPlotFlags_NoLegend)) {
    ImPlot::PlotDummy("Item 1");
    ImPlot::PlotDummy("Item 2");
    ImPlot::PlotDummy("Item 3");
    ImPlot::EndPlot();
}
if (pos == Right)  { ImGui::SameLine(); ImPlot::ShowAltLegend("##Legend",ImPlotOrientation_Vertical,ImVec2(0,300)); }
if (pos == Bottom) { ImPlot::ShowAltLegend("##Legend",ImPlotOrientation_Horizontal,ImVec2(500,0));                  }
```

I can't decide if I love it, or hate it...

**Comment by ArekSredzki** [comment]
That's awesome. I assume it works well with automatic plot widths as long as the legend isn't on the side. I suppose it should be easy for everything but the `Right` option, correct?

What happens on the first frame, before the specified table has been drawn?
That's especially relevant for the cases where `ImGui::SameLine()` has been used.

**Comment by epezent** [comment]
> That's awesome. I assume it works well with automatic plot widths as long as the legend isn't on the side. I suppose it should be easy for everything but the Right option, correct?

Basically. Top and Bottom will work with (-1,0). Left will work with (0,0). Right is difficult because you have to explicitly size the plot first.

> What happens on the first frame for Left & Top, where ShowAltLegend is called before the specified table has been drawn?

It will draw the frame (med. gray background), but not the legend inlay (dark gray background). If 0 is used for the size parameter, then you will see the plot position jump on the second frame. If you explicitly set the size, then it won't jump and you'll only see the inlay appear. That said, both are barely noticeable at 60 FPS.

**Comment by ArekSredzki** [comment]
Excellent, thanks so much!

**Comment by epezent** [comment]
You are welcome! 

It's not a perfect solution, but it does accomplish what we wanted. On one hand, `ShowAltLegend` seems like it could be flexible for other use cases (e.g. rendering legend/controls in another part of the window), but on the other hand I feel like no one will use it for anything except rendering the legend directly outside of the plot area, so I might as well just support that with `SetLegendLocation`. 

I'm going to spend a few more hours seeing if I can make this work with just `SetLegendLocation`. It would just much simpler from an API standpoint. If I can't get it working soon, I'll merge it as is with `ShowAltLegend`.

**Comment by epezent** [comment]
With all the refactors I made for `ShowAltLegend`, it actually wasn't too bad just making this all work with `SetLegendLocation`. Therefore, I've removed `ShowAltLegend` (it's in `implot_internal.h` for now), and changed the signature of `SetLegendLocation`:

```cpp
IMPLOT_API void SetLegendLocation(ImPlotLocation location, ImPlotOrientation orientation = ImPlotOrientation_Vertical, bool outside = false);
```

It simply works the way you would expect it to! 

![legend](https://user-images.githubusercontent.com/29577475/96402005-79247400-119a-11eb-9b35-f6261f770ec5.gif)

I've merged this to master, so I'll be closing this issue. @ArekSredzki , please let me know if you have any issues. Thanks for the great suggestion!
