### ISSUE TITLE
Plots not vertically resizing

### ISSUE THREAD

**Issue by z-adams** [epezent/implot#134]
This is likely the result of something I'm doing wrong rather than an actual bug, but I can't find any other way to determine this for sure.

Based on what I've read and the screenshots I've seen here, it seems like plots are supposed to resize to fill the ImGui window they occupy. For whatever reason, my plots are limited to a horizontally wide but vertically narrow strip. I'm trying to get a big square plot, and it correctly resizes horizontally to fill the width of the window, but its vertical size remains fixed.

I've seen screenshots that show square-er plots or even tall vertical ones that run the height of the screen in multiple columns; does the behavior I'm expecting require the ImGui tables branch, am I missing some basic configuration step, or is there actually something wrong with my build? I am using the Magnum graphics engine ImGui integration so it's possible there's some interference from that.

The code is about as basic as can be:
```cpp
if (ImPlot::BeginPlot("Phase Space (x)", "x", "dx/dt"))
{
    ImPlot::SetNextMarkerStyle(ImPlotMarker_Circle);
    ImPlot::PlotLine("Earth", psX, psY, psIdx);
    ImPlot::EndPlot();
}
```
Any insight would be appreciated, thanks.

**Comment by marcizhu** [comment]
By default `BeginPlot()` creates a plot that resizes in the X axis, but not in the Y axis, which is what's happening to you. To fix it, tell it to resize in both axis by passing `ImVec2(-1, -1)` as the size of the plot:
```cpp
if (ImPlot::BeginPlot("Phase Space (x)", "x", "dx/dt", ImVec2(-1, -1)))
{
    ImPlot::SetNextMarkerStyle(ImPlotMarker_Circle);
    ImPlot::PlotLine("Earth", psX, psY, psIdx);
    ImPlot::EndPlot();
}
```

With this small change, your issue should be fixed! :D
Btw, if you want more insight in the parameters and options for each API call, please refer to the [implot.h](https://github.com/epezent/implot/blob/master/implot.h) header file.
