### ISSUE TITLE
Consecutive BeginPlot() 

### ISSUE THREAD

**Issue by sayan1an** [epezent/implot#137]
I am having trouble showing two separate plots consecutively one after the other. The second plot does not show in the UI pane. However, if I comment out the first plot, the second plot works fine.

Screenshot of the issue attached here!

![plotErr](https://user-images.githubusercontent.com/1608941/96630145-97958700-12e2-11eb-8da9-e03264ea3f35.png)

```
                                ImGui::SetNextPlotRange(0, 1.0f, 0, 1.0f, ImGuiCond_Always);
				if (ImGui::BeginPlot("Gauss approx Plot##MarkovChainPass", "u", "v")) {
					ImGui::PushPlotStyleVar(ImPlotStyleVar_LineWeight, 0);
					ImGui::PushPlotStyleVar(ImPlotStyleVar_Marker, ImMarker_Circle);
					ImGui::PushPlotStyleVar(ImPlotStyleVar_MarkerSize, 4);

					ImGui::Plot("Mean##MarkovChainPass", &meanVar[0], 1);
					ImGui::Plot("Std-X##MarkovChainPass", &meanVar[1], 2);
					ImGui::Plot("Std-Y##MarkovChainPass", &meanVar[3], 2);

					ImGui::PopPlotStyleVar(3);
					ImGui::EndPlot();
				}

				ImGui::SetNextPlotRange(0, 1.0f, 0, 1.0f, ImGuiCond_Always);
				if (ImGui::BeginPlot("Scatter Plot##MarkovChainPass", "u", "v")) {
					ImGui::PushPlotStyleVar(ImPlotStyleVar_LineWeight, 0);
					ImGui::PushPlotStyleVar(ImPlotStyleVar_Marker, ImMarker_Circle);
					ImGui::PushPlotStyleVar(ImPlotStyleVar_MarkerSize, 4);
					auto getter = [](const void* data, int idx) {
						glm::vec4 d = static_cast<const glm::vec4*>(data)[idx + SAMPLE_HEADER_SIZE];
						//std::this_thread::sleep_for(std::chrono::milliseconds(100));
						return ImVec2(d.x, d.y);
					};
					ImGui::Plot("Samples##MarkovChainPass", static_cast<ImVec2(*)(const void*, int)>(getter), static_cast<const void*>(ptrCollectMcSampleBuffer), static_cast<int>(ptrCollectMcSampleBuffer[1]), 0);
					
					ImGui::PopPlotStyleVar(3);
					ImGui::EndPlot();
				}
```

**Comment by ozlb** [comment]
implot_demo.cpp includes your scenario and "over comprehensive".
In detail:
https://github.com/epezent/implot/blob/eb935d0b4f2fa54750d156884618b93eb84e6a27/implot_demo.cpp#L780

In your specific case, i think that the issue is related to the plot unique ID that is not unique, actually is the same for both plots: `MarkovChainPass` and exaplains also the reason why if you comment first the second works fine.

**Comment by sayan1an** [comment]
It still doesn't work. I changed the following.
Has it something to do with ImGuiCond_Always?
```
ImGui::BeginPlot("Gauss approx Plot##MarkovChainPass_1", "u", "v")
ImGui::BeginPlot("Gauss approx Plot##MarkovChainPass_2", "u", "v")
```

**Comment by epezent** [comment]
@sayan1an, what version are you using? I ask because `SetNextPlotRange` became `SetNextPlotLimits` some time ago, and we moved everything into the `ImPlot::` namespace in v0.2. Please update to the latest version if possible.

Using the latest version, I have no issues:

```
ImGui::Begin("Two Plots");
ImPlot::SetNextPlotLimits(0, 1.0f, 0, 1.0f, ImGuiCond_Always);
if (ImPlot::BeginPlot("Gauss approx Plot##MarkovChainPass", "u", "v")) {
    ImPlot::EndPlot();
}
ImPlot::SetNextPlotLimits(0, 1.0f, 0, 1.0f, ImGuiCond_Always);
if (ImPlot::BeginPlot("Scatter Plot##MarkovChainPass", "u", "v")) {
    ImPlot::EndPlot();
}
ImGui::End();
```
![image](https://user-images.githubusercontent.com/29577475/96644304-7a66b580-12ee-11eb-8e33-e5f7a3286cc1.png)

**Comment by sayan1an** [comment]
After the update and some modifications according to the changes in API, I am hitting the following assert in SetNextPlotLimits()- 
`IM_ASSERT_USER_ERROR(GImPlot->CurrentPlot == NULL, "SetNextPlotLimits() needs to be called before BeginPlot()!");`

The function is called before BeginPlot().

**Comment by epezent** [comment]
You must be forgetting an `EndPlot` somewhere.

**Comment by sayan1an** [comment]
Adding CreateContext()/DestroyContext() fixed the issue. Thank you all!

I understand that this is an experimental API in its early stages but moving forward do we expect any major updates to the ImPlot API interface?

**Comment by epezent** [comment]
I won't make any guarantees until we hit v1.0, but certainly not to the extent that you witnessed going from 0.2 to 0.8. I'm doing my best to keep it stable moving forward and document API breaking changes. Thanks for your patience! Glad you figured out the issue.
