### ISSUE TITLE
ImPlot::AddTextVertical and superscript numbers (utf8)

### ISSUE THREAD

**Issue by terewenko** [epezent/implot#139]
Hello,
An error occurs when adding vertical text that contains superscript numbers.
>IM_ASSERT(draw_list->VtxBuffer.Size == 0 || draw_list->_VtxWritePtr == draw_list->VtxBuffer.Data + draw_list->VtxBuffer.Size);

Example:
ImPlot::AddTextVertical(ImGui::GetWindowDrawList(), ImGui::GetCursorScreenPos(), IM_COL32(255, 255, 255, 255), u8"\u00B2");

**Comment by epezent** [comment]
Thanks, I'll try to take a look when time allows. Any PRs from others would be helpful.

**Comment by epezent** [comment]
This has been fixed (https://github.com/epezent/implot/commit/6e2499093b8437fad67fdb7570ef9cb207e7e51c). Superscripts (and presumably other utf8 encoded strings) should work in all possible locations:

![image](https://user-images.githubusercontent.com/29577475/105115288-2191ef00-5a8e-11eb-9cc7-90e1d5441010.png)
