### ISSUE TITLE
AddTicksTime wrong definition

### ISSUE THREAD

**Issue by sonoro1234** [epezent/implot#150]
in implot.cpp
void AddTicksTime(const ImPlotRange& range, float plot_width, ImPlotTickCollection& ticks)
in implot_internal
IMPLOT_API void AddTicksTime(const ImPlotRange& range, int nMajor, ImPlotTickCollection& ticks);

see https://github.com/mellinoe/ImGui.NET/pull/218#issuecomment-736482969

**Comment by epezent** [comment]
Fixed: https://github.com/epezent/implot/commit/24b543839be2761a0a8d1b764f7527dccf6060a8
