### ISSUE TITLE
Padding for double-click fitting

### ISSUE THREAD

**Issue by mindv0rtex** [epezent/implot#151]
Is it possible to control the auto-fitting when double-clicking the chart area? I would like to leave some room around the plotted line after fitting.

**Comment by epezent** [comment]
Not currently. It's a reasonable idea, so I'm open to API suggestions. My first thought is as a normalized ImVec2 style variable, e.g. ImVec2(1.1f,1.1f) gives you 10% padding in x and y. Thoughts?

**Comment by mindv0rtex** [comment]
I would say that for padding it would be more intuitive to have the 0.0 value correspond to no padding. So I'd say `ImVec2(0.1f, 0.1f)` for 10% padding.

**Comment by epezent** [comment]
Yes, I suppose that is more intuitive!

**Comment by epezent** [comment]
Done: https://github.com/epezent/implot/commit/fa10a03a53367ae9e112ec7cb3b62f0360514455

![fitpadd](https://user-images.githubusercontent.com/29577475/101125711-8321fb00-35bf-11eb-9a0e-6e54b07135b6.gif)

**Comment by epezent** [comment]
FYI, ImVec2(0.1f,0.1f) adds 10% of the pre-padded extents to the total extents (i.e. 5% padding on left/right or top/bottom).

**Comment by mindv0rtex** [comment]
While we are still n the subject, I think the fitting of constant data is not quite right. It fits the entire line along the bottom axis, but I believe it should be centered vertically instead, with some default padding, like +- 0.5.

**Comment by epezent** [comment]
I recall noticing that but never got around to fixing it. Can you open a new issue or submit a PR?

**Comment by mindv0rtex** [comment]
I'll give it a try!
