### ISSUE TITLE
Bad definitions

### ISSUE THREAD

**Issue by sonoro1234** [epezent/implot#153]
Hi Evan,

I found another bad definitions while wrapping implot intenal:

`IMPLOT_API void UpdateAxisColors(int axis_flag, ImPlotAxisColor* col);`
vs
`void UpdateAxisColors(int axis_flag, ImPlotAxis* axis)`

`IMPLOT_API void ShowAxisContextMenu(ImPlotAxisState& state, bool time_allowed = false);`
vs
`void ShowAxisContextMenu(ImPlotAxis& axis, ImPlotAxis* equal_axis, bool time_allowed)`

also 

`ImBufferWriter:Write` should have `ImBufferWriter:WriteV` va_list companion (as in https://github.com/epezent/implot/commit/b5cf8b8431f46eb1e9e97070dcfd4c4f57162ae9)

Or it could be skipped if you prefer

**Comment by epezent** [comment]
Thanks, this must have happened when I updated axes a while back. I'll get this tidied up tonight.

**Comment by epezent** [comment]
Fixed: https://github.com/epezent/implot/commit/b22c21f9121ba85a29328fa65ddf91c44677a7b6

Close if this resolves all your issues.

**Comment by sonoro1234** [comment]
Solved!!
