### ISSUE TITLE
Plot vertical lines

### ISSUE THREAD

**Issue by bear24rw** [epezent/implot#155]
In my time series plot I have events which I would like to indicate as vertical lines. Ideally these lines would always span the whole y range but wouldn't affect the y scaling. `PlotStems` is very close to what I'm looking for but it takes in a height and also draws a circle marker. I'm not sure if its better to add an explicit `PlotVerticalLines` function or allow passing a null pointer to y values parameter of `PlotStems` to indicate the stem should always cover the full y range (and make circle marking optional).

**Comment by ddovod** [comment]
It's very easy to achieve this with code
```cpp
auto xValue = 12.0;
if (ImPlot::BeginItem("Some id")) {
    const auto& limits = ImPlot::GetPlotLimits();
    auto p1 = ImPlot::PlotToPixels(xValue, limits.Y.Min);
    auto p2 = ImPlot::PlotToPixels(xValue, limits.Y.Max);
    ImPlot::PushPlotClipRect();
    ImPlot::GetPlotDrawList()->AddLine(p1, p2, ImColor{0xCC, 0x66, 0x66, 0xaa});
    ImPlot::PopPlotClipRect();
    ImPlot::EndItem();
}
```
You can wrap it with helper function. This code draws vertical line at `xValue` from the top to the bottom of the plot no matter how the plot is scaled now.

**Comment by epezent** [comment]
Note we have `DragLineX` for interactive vertical lines. 

It would also be really easy for us to add something similar to matplotlib `hlines` and `vlines`

https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.vlines.html#matplotlib.pyplot.vlines

**Comment by bear24rw** [comment]
> It's very easy to achieve this with code

Thanks! That's definitely a good option, I think I'll try this for now. 

> It would also be really easy for us to add something similar to matplotlib hlines and vlines

Yes an equivalent to `axvline` is exactly what I'm looking for! (but be able to take an array of x values)

**Comment by epezent** [comment]
`PlotVLines` and `PlotHLines` were added with #166!

![inf](https://user-images.githubusercontent.com/29577475/104697001-b387a980-56d4-11eb-8acf-2b87316d04ce.gif)
