### ISSUE TITLE
Some assistance integrating into ogre 3d

### ISSUE THREAD

**Issue by kenkit** [epezent/implot#159]
https://github.com/OGRECave/ogre/pull/1812

**Comment by epezent** [comment]
See my comment on the PR. Closing this issue.

**Comment by kenkit** [comment]
@epezent 
This is the solution that worked since I guess ogreoverlay is a dll
https://github.com/kenkit/ogre-1/commit/09a87d48cd17bc2d5cad842ca927556e69622735
