### ISSUE TITLE
Announcements and New Features (2021)

### ISSUE THREAD

**Issue by epezent** [epezent/implot#164]
Announcements of changes and new features will be posted here. Click `Subscribe` to the right to receive updates!

## PLEASE DO NOT COMMENT ... EMOJIS ARE WELCOME :)

Previous Announcements:
[Announcements and New Features (2020)](https://github.com/epezent/implot/issues/48)

**Comment by epezent** [comment]
## Labels for Auxiliary Y-Axes - (v0.9 - 1/6/2021)

Labels can now be added to the second and third y-axes by passing strings to `BeginPlot`. Additionally, `ImPlotAxisFlags_NoLabel` has been added and a context menu toggle is provided.

![](https://user-images.githubusercontent.com/10409817/103726193-525e2880-4fa6-11eb-843a-7834bbda4880.png)

Special thanks to @mindv0rtex!

**Comment by leeoniya** [comment]
usually the label baseline is on the chart side of the axis. (in the image, the right axis labels need 180deg rotation)

**Comment by mindv0rtex** [comment]
> usually the y axis label baseline is on the chart side of the axis. (in the image, the right axis labels need 180deg rotation)

Not so in matplotlib and gnuplot, which are the libraries I'm aware of.

**Comment by leeoniya** [comment]
huh, according to google image search, you're right and i'm definitely wrong. for some reason it feels unnatural to me to have the label on the left with the baseline against the values and not have a mirrored layout on the right.

**Comment by epezent** [comment]
I am moving Announcements to GitHub Discussions.

**Comment by epezent** [comment]
See #168
