### ISSUE TITLE
How to nan/empty_value skipping plotting?

### ISSUE THREAD

**Issue by kv-gits** [epezent/implot#169]
Have some data with shared time axis and some of this data is gapped. How to make spaces in plotting it?

**Comment by kv-gits** [comment]
```
xs1[i] = (float)i;
ys1[i] = std::nan("1");
```
Works nice

**Comment by epezent** [comment]
To be clear, ImPlot does not officially support gapped data or NaNs. I'm not sure what is happening with the code above, but if it works for you without bugs, then great! Hopefully this will be properly addressed in the future.
