### ISSUE TITLE
Custom labels with lambda

### ISSUE THREAD

**Issue by kv-gits** [epezent/implot#173]
Is it possible to set custom label not only with predefined array, but with c++ lambda?

**Comment by epezent** [comment]
Not currently. But that's not a bad idea. We could easily support it.

**Comment by epezent** [comment]
@kv-gits, I've add the ability to set custom tick format specifiers in #198. Does something like this support your use case, or would you still require a callback? If so, can you describe what your ideal callback signature would be, i.e. what information would you require to generate the ticks? (e.g. plot range, pixel size, etc).

**Comment by kv-gits** [comment]
Sorry, I missed this issue. I think callback should be as it is already implemented for Y values

auto lamda = [](void* data, int idx) { ... return "const char array"; };

So we could consider e.g. scale and prepare appropriate format inside lambda.

**Comment by epezent** [comment]
#294 (see also https://github.com/epezent/implot/discussions/168#discussioncomment-1505784) adds:

```cpp
// Sets the format of numeric axis labels via formatter callback. Given #value, write a label into #buff. Optionally pass user data.
void SetupAxisFormat(ImAxis axis, ImPlotFormatter formatter, void* data = NULL);
```

where:

```cpp
// Callback signature for axis tick label formatter.
typedef void (*ImPlotFormatter)(double value, char* buff, int size, void* user_data);
```

example:

```cpp
void MetricFormatter(double value, char* buff, int size, void* data) {
    const char* unit = (const char*)data;
    static double v[]      = {1000000000,1000000,1000,1,0.001,0.000001,0.000000001};
    static const char* p[] = {"G","M","k","","m","u","n"};
    if (value == 0) {
        snprintf(buff,size,"0 %s", unit);
        return;
    }
    for (int i = 0; i < 7; ++i) {
        if (fabs(value) >= v[i]) {
            snprintf(buff,size,"%g %s%s",value/v[i],p[i],unit);
            return;
        }
    }
    snprintf(buff,size,"%g %s%s",value/v[6],p[6],unit);
}
```

```cpp
if (ImPlot::BeginPlot("MyPlot")) {
    ImPlot::SetupAxisFormat(ImAxis_Y1, MetricFormatter, (void*)"Hz");
    ImPlot::EndPlot();
}
```

![img](https://user-images.githubusercontent.com/29577475/137953519-d46cef58-68c4-4251-bec4-464d52be105a.gif)
