### ISSUE TITLE
Add scrollbar to legend

### ISSUE THREAD

**Issue by yaszin** [epezent/implot#177]
Is it possible to add a scrollbar or something similar inside the legend in order to view all dataset names when plotting multiple lines ?

**Comment by epezent** [comment]
It's not currently possible and I have no plans to support it in the near-term. I'm happy to review PRs if you'd like to give it a shot.

As an alternative, you can try 1) setting the legend location to outside with `SetLegendLocation` -- this may buy you a little extra room or 2) rendering your own legend in an ImGui window or table (see our drag and drop demo for a comparable example).

**Comment by epezent** [comment]
@yaszin, please also see `ShowAltLegend` in `implot_internal.h`. IIRC, my intention was to eventually move this into the public API but I never got around to testing it thoroughly.

**Comment by epezent** [comment]
https://github.com/epezent/implot/pull/504
