### ISSUE TITLE
rand(), srand() and RAND_MAX not found

### ISSUE THREAD

**Issue by sayan1an** [epezent/implot#18]
The above functions used in the demo is causing issues on c++11/17 compilers. A trivial fix is to use the new style headers but that violates Dear ImGui's strict compliance with pre c++11 feature set.

Any ideas other than keeping a separate fork for C++11?

**Comment by sonoro1234** [comment]
Every C++11 compiler can be given a flag for changing the standard

**Comment by epezent** [comment]
I use the latest MSVC compiler with 17 enabled and don't have any issues. What flags are you using? Also, can you investigate how ImGui deals with these issues? We want to be as conformant with ImGui as possible.

**Comment by sayan1an** [comment]
@epezent Yes, ImGui compiles without any modification. I think the problem is just a missing header.
