### ISSUE TITLE
How to force resize without double clicking

### ISSUE THREAD

**Issue by peterwilson136** [epezent/implot#190]
I am having trouble finding out how to automatically resize a plot when I need it to (aside from double clicking), it needs to do the exact same job that double clicking on a plot does, but when I call it as well. For example, if I add new data to a graph, I want to have something like
```
if (dataAdded){
    ImPlot::ResizePlot(); 
}
```
where it sizes the entire plot and scale to fit the grid as if it is simulating what double clicking on a plot does exactly. 
I have tried `ImPlot::SetNextPlotLimits` but it doesn't seem to work when I modify data. What can I do to simulate a double click resize but in some code, rather than event handling?
Thanks!

**Comment by yamen** [comment]
What you want is `FitNextPlotAxes` 
https://github.com/epezent/implot/blob/46ea9abab4bb8b5fb60ce6b61f6e5c1bf2e840c1/implot.h#L457-L458

From demo:
https://github.com/epezent/implot/blob/46ea9abab4bb8b5fb60ce6b61f6e5c1bf2e840c1/implot_demo.cpp#L726-L730

**Comment by peterwilson136** [comment]
Awesome! Thank you very much.
