### ISSUE TITLE
Normalize Heatmap Colors Along Each Row or Column

### ISSUE THREAD

**Issue by alandefreitas** [epezent/implot#191]
Is it possible to normalize heatmap colors along each row or column?

I have a heatmap comparing a number of indicators and it would be extremely useful to have something [like this](https://www.mathworks.com/help/matlab/ref/heatmap.html#bvlbn9r-1).

I thought it would be possible by replacing the heatmap labels and using normalized numbers just for the colors. But I'm not sure that's really possible.

**Comment by epezent** [comment]
@alandefreitas, my initial reaction was to suggest that you pre-normalize the data to your liking, but I see now that you need the *color* to be scaled independently for each row or column. That is not currently a feature we support. The library is still evolving, and so nuances such as this haven't been addressed yet.

However, I have a not-so-terrible solution for you! First, pull the latest master. I just pushed a small change to PlotHeatmap that automatically determines the minscale and maxscale by default (I'm not sure why I didn't do this already): https://github.com/epezent/implot/commit/eea12d6b4c22bdcd5898b106fdecf1b01accaa37

Now, make a helper function that plots each row as a separate heatmap. Double check my implementation and modify as you see fit. Changing this to do column scaling should be trivial.

```cpp
void PlotHeatmap_ScaledRows(const char* id, double* values, int rows, int cols,const char* fmt="%.1f") {
    const double ht = 1.0 / rows;
    for (int r = 0; r < rows; ++r) {
        ImPlotPoint bmin(0,1-(r+1)*ht);
        ImPlotPoint bmax(1,1-r*ht);
        ImPlot::PlotHeatmap(id,&values[r*cols],1,cols,0,0,fmt,bmin,bmax);
    }
}
```

Then use it as you would the regular version:

```cpp
ImGui::Begin("Test");
double data[] = {1,2,3,4,5,6,7,8,9,10,11,12};
ImPlot::PushColormap("Viridis");
if (ImPlot::BeginPlot("Regular")) {
    ImPlot::PlotHeatmap("##test",data,4,3);
    ImPlot::EndPlot();
}
if (ImPlot::BeginPlot("Row Scaled")) {
    PlotHeatmap_ScaledRows("##test",data,4,3);
    ImPlot::EndPlot();
}
ImPlot::PopColormap();
ImGui::End();
```

![image](https://user-images.githubusercontent.com/29577475/111858745-e92d5680-8900-11eb-9cf6-f7d151bdc1d5.png)

**Comment by alandefreitas** [comment]
@epezent Thanks for the feedback. I'll definitely try that. I didn't really think there would be a function just for that, but I thought someone more familiar with the internals of the library would be able to achieve the same results by combining some other functions. 

Happy to know that was true. I'll adapt your implementation as soon as I can and give you some feedback. I had already implemented some wrappers to normalize the data and to set the scale automatically. The only small problem I had was I had to make sure `minscale != maxscale`. I think it's more common to just attribute the same color to all cells in that case.

That row/column normalization problem had probably not come up yet over here, but that's a quite common use case, because columns and rows very very very very often represent different units. If you want to see the labels, normalizing the data doesn't solve the problem because the labels would lose their meaning.

Thanks for that 😄

**Comment by alandefreitas** [comment]
I just tried it and it worked perfectly. Because I needed to scale by column in my problem, the final snippet looked like:

```cpp
const double wt = 1.0 / n_cols;
for (size_t c = 0; c < n_cols; ++c) {
    std::vector<float> column_data;
    for (size_t r = 0; r < n_rows; ++r) {
        column_data.emplace_back(contiguous_table[r * n_cols + c]);
    }
    ImPlotPoint bmin(wt * c, 0);
    ImPlotPoint bmax(wt * (c + 1.), 1.);
    auto [min_el, max_el] =
    std::minmax_element(column_data.begin(), column_data.end());
    double scale_min = min_el != column_data.end() ? *min_el : 0.;
    double scale_max = max_el != column_data.end() ? *max_el : 0.;
    if (scale_min == scale_max) {
        scale_max += 1.0;
    }
    ImPlot::PlotHeatmap(label.data(), column_data.data(), n_rows, 1, scale_min, scale_max, "%.1f", bmin, bmax);
}
```

It looks beautiful 😀

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/5369819/111889103-222d0000-89c1-11eb-9508-058b2cd43dae.png">
