### ISSUE TITLE
FitNextPlotAxes only works for 3 plots

### ISSUE THREAD

**Issue by prateekma** [epezent/implot#193]
I'm developing a program where I'd like to show more than 4 plots in a row. The plots would have FitNextPlotAxes() called once when they are loaded and then I want to let the user zoom in as they like. However, the code below only works for the first three plots; subsequent plots are not autoscaled at all.

```
  void Display() override {
    int x[51];
    int y[51];
    for (int i = -25; i <= 25; ++i) {
      x[i + 25] = i;
      y[i + 25] = i;
    }

    if (m_firstRun) {
      ImPlot::FitNextPlotAxes();
    }
    if (ImPlot::BeginPlot("A")) {
      ImPlot::PlotScatter("A1", x, y, 51);
      ImPlot::EndPlot();
    }

    if (m_firstRun) {
      ImPlot::FitNextPlotAxes();
    }
    if (ImPlot::BeginPlot("B")) {
      ImPlot::PlotScatter("B1", x, y, 51);
      ImPlot::EndPlot();
    }

    if (m_firstRun) {
      ImPlot::FitNextPlotAxes();
    }
    if (ImPlot::BeginPlot("C")) {
      ImPlot::PlotScatter("C1", x, y, 51);
      ImPlot::EndPlot();
    }

    if (m_firstRun) {
      ImPlot::FitNextPlotAxes();
    }
    if (ImPlot::BeginPlot("D")) {
      ImPlot::PlotScatter("D1", x, y, 51);
      ImPlot::EndPlot();
    }

    if (m_firstRun) {
      m_firstRun = false;
    }
  }
```

**Comment by epezent** [comment]
@prateekma, what I believe is happening is that your 4th plot is not visible in the ImGui window on initialization. Thus, `ImPlot::BeginPlot("D")` returns `false`, which means that the data is never submitted and `EndPlot` is never called (which is where fitting takes place). As you can see, each is fitted for me if I make the window large enough:

![image](https://user-images.githubusercontent.com/29577475/111858043-7372bc00-88fb-11eb-96d3-df8e3bc7acba.png)

But if I make the window initially smaller, even the 3rd plot is not fit:

![image](https://user-images.githubusercontent.com/29577475/111858063-9a30f280-88fb-11eb-8b8d-17ce40b62301.png)

This isn't a bug per se, but rather the fallout of how ImPlot is designed. As a work around, you may need to introduce a bool for each plot and clear it *inside* of the `BeginPlot` if statement.

I'll leave the issue open for now, as we likely have other functions that affected by this phenomenon, and there may be a clean way we can handle it internally. Thanks for bringing this to my attention!

**Comment by epezent** [comment]
One possible idea is for us to introduce a `ImPlotAxisFlags_FitOnInit` or something to that effect. We may even want this to be the default behavior for newly created plots.

**Comment by prateekma** [comment]
Ah, that makes perfect sense, thanks! Yep, adding a flag like that would be even more convenient.

**Comment by epezent** [comment]
@prateekma , I've added initial fitting for newly created plots. Please see https://github.com/epezent/implot/discussions/168#discussioncomment-509049. You should be able to remove all of your boilerplate code. If this satisfies your needs, please close the issue. Thanks!

**Comment by prateekma** [comment]
Thank you!
