### ISSUE TITLE
Implot shows only two of four opened collapsed headers with plots at the same time

### ISSUE THREAD

**Issue by kv-gits** [epezent/implot#194]
![5m2tFJfyf6](https://user-images.githubusercontent.com/26402310/111900134-cb1b3f80-8a41-11eb-9b50-92a1c6f42830.gif)

All this plots initialised the same way like this

```
if (ImGui::CollapsingHeader("T1")) {
        if (ImPlot::BeginPlot("Test")) {
            ImPlot::PlotLine("RI_C", RI_С.data(), RI_С.size());
            ImPlot::PlotLine("RegRender", RI_REGMID.data(), RI_REGMID.size());
            ImPlot::EndPlot();
        }
}
```

Also if I add other widget like text to the headers, it is showed properly

**Comment by epezent** [comment]
I don't believe `ImGui::CollapsingHeader` pushes an ID onto the stack like a window or child window would. Therefore, you need to use different labels for each of your plots, e.g. "Test1", "Test2". or "##Test1", "#Test2". The ImPlot demo makes extensive use of collapsing headers without issue.

**Comment by kv-gits** [comment]
That is true! I used empty string as label. Thanks!
