### ISSUE TITLE
Making square heatmaps?

### ISSUE THREAD

**Issue by Tjakka5** [epezent/implot#196]
I'm trying to model a real world magnetic field within a square area and display it with the heatmap widget.
All is working well. But the axis are not equally sized, causing the whole image to look wonky.
How would I make both axis equal length such that the resulting image will be square?

I've attached an image of what I want (left) and what I currently have (right).

![image](https://user-images.githubusercontent.com/10415640/111960166-aaa9be80-8aef-11eb-81d2-421369ba0699.png)

Additionally, is it possible to supply a colormap manually? I'd like a bit more control over which ranges of values turn into which colors.

**Comment by epezent** [comment]
Both are possible. See `ImPlotFlags_Equal` and `AddColormap` respectively.
