### ISSUE TITLE
How to link plots together

### ISSUE THREAD

**Issue by peterwilson136** [epezent/implot#199]
Is there anyway for me to have 2 plots, exactly the same amount of X values (but different Y), linked together such that moving / zooming in on one plot modifies the other plot (by the exact same amount), but not vice versa. So for example, I have Plot A, Plot B, when I move Plot A, it moves Plot B. When I zoom in on Plot A, it zooms in on Plot B (but I need to be able to control the scale after zooming). But now when I zoom in on Plot B, nothing happens to either (this is what I want). And also when I click on and drag Plot B, nothing happens to either. <- Basically, whatever I do to Plot B does not affect Plot A (but I also want to block moving and zooming for plot B by the mouse), but whatever I do to plot A affects Plot B.

**Comment by epezent** [comment]
I think this can be simply acheived with:

```cpp
ImPlotLimits limits;

if (ImPlot::BeginPlot("A",...)) {
    limits = ImPlot::GetPlotLimits();
    ImPlot::EndPlot();
}

ImPlot::SetNextPlotLimits(limits.X.Min,...,ImGuiCond_Always);
if (ImPlot::BeginPlot("B",...)) {
    ImPlot::EndPlot();
}
```

`ImGuiCond_Always` will lock "B" from any input.

Let me know how far this gets you.

**Comment by peterwilson136** [comment]
When I move Plot A with my mouse, it doesn't change anything. 

```
if (ImPlot::BeginPlot("A", "X", "Y", ImVec2(-1, 0), ImPlotFlags_NoBoxSelect | ImPlotFlags_AntiAliased, ImPlotAxisFlags_Time)) {

        //Plotting something here
        m_PlotLimits = ImPlot::GetPlotLimits();

        ImPlot::EndPlot();
}

ImPlot::SetNextPlotLimits(m_PlotLimits.X.Min, m_PlotLimits.X.Max, m_PlotLimits.Y.Min, m_PlotLimits.Y.Max);
if (ImPlot::BeginPlot("B", "X", "Y", ImVec2(-1, 0), ImPlotFlags_NoBoxSelect | ImPlotFlags_AntiAliased, ImPlotAxisFlags_Time)) {
       
        //Plotting something here

        ImPlot::EndPlot();
}
```

**Comment by peterwilson136** [comment]
I deleted the previous comment, I forgot to add that flag. Thank you very much. Works perfectly.

**Comment by peterwilson136** [comment]
If its alright, I have an additional question as an extension to this. If my Y values are different in Plot B, how can I make it so when I zoom in on Plot A, the Y values range adapts. So for example, if I have an array of doubles such as 
```
double plot_b_y_values[] = {1,2,4,5,7,78,1,56,2,13,7,16,62,6,8,123,6,13,123}; //Or something of this sort
```
and when I zoom in on Plot A, the entire range of Plot B y values might not be shown in the graph, for example, a portion of them, say [5, 10] or something. Basically replicating `ImGuiListClipper` but for the graphs. I need it to set the Y range of Plot B equal to the minimum of that range, to the maximum of that range if that makes sense?

**Comment by epezent** [comment]
Try setting only the x-limits of B from A and flagging `ImPlotAxisFlags_AutoFit` for B y-axis:

```cpp
ImPlotLimits limits;

if (ImPlot::BeginPlot("A",...)) {
    limits = ImPlot::GetPlotLimits();
    ImPlot::EndPlot();
}

ImPlot::SetNextPlotLimitsX(limits.X.Min,limits.X.Max,ImGuiCond_Always); // only X derived from A
if (ImPlot::BeginPlot("B","x","y",ImVec2(0,0),0,0,ImPlotAxisFlags_AutoFit)) {
    ImPlot::EndPlot();
}
```

**Comment by peterwilson136** [comment]
There is no ImPlotAxisFlags_AutoFit for me

**Comment by epezent** [comment]
Recently added. Either update your lib or alternatively use `ImPlot::FitNextPlotLimits(false,true,false,false);` before B.

**Comment by peterwilson136** [comment]
Ok I updated it, thanks for the response. It's just missing the adaptation of a specified range of values. It resizes the Y axis to fit the minimum and maximum of the entire array, rather than the portion that it is displaying.

**Comment by epezent** [comment]
@peterwilson136 , please see #200. Please close the issue if `ImPlotAxisFlags_AutoFit|ImPlotAxisFlags_RangeFit` meets your needs. Thanks!

**Comment by peterwilson136** [comment]
Yes it did! Thank you very much for your help!

**Comment by peterwilson136** [comment]
Sorry can I also extend this once more? I am just wondering as well, how to link these such that either Plot you move will move the other the same amount. So Plot B can move Plot A and vice versa.

**Comment by epezent** [comment]
See `LinkNextPlotLimits` and associated demo. Please search the library, demo, and issues more thoroughly in the future.
