### ISSUE TITLE
Multi-Axis Support

### ISSUE THREAD

**Issue by epezent** [epezent/implot#20]
Moving discussions of multi-axis support to a separate issue. Previous comments below:

https://github.com/epezent/implot/issues/1#issuecomment-626177655

**Comment by epezent** [comment]
> I wasn't planning on it, and haven't seen it supported in other tools, like matplotlib. In any event, I don't think this work would preclude later generalization to more than one x axis.

Sounds good to me. We can wait and see if it's something that people absolutely need before we decide to support it. 

> Heh. I use 3 pretty often, and have actually used 4 on occasion, although I can usually live without with more contortions. Granted, more than 2 (and more than 1) can also be somewhat emulated by having multiple separate plots with linked x axes. That just makes it harder sometimes to see the relations if you can't squish things around to be appropriately close together.

Ok, I'm fine with three being the hard max. I don't normally use them myself, so I have no real say here. 

> I was planning on just having them enable independently. In that regime, it would be admittedly somewhat silly to select y3 without y2. I'm not sure any alternatives I can think of are any better:
> 
> * Throw an error if y3 is enabled without y2
> * Make the flags be mutually exclusive and mean "2 axes" and "3 axes"
> * Add yet another parameter to `BeginPlot` with number of y axes

Yea, I agree. I kind of like the second option, but I don't think it really matters honestly. Both could be abused if the user really tried. You can keep it as is.

> I was planning to have it display all enabled axes simultaneously, like "%f,%f,%f,%f" if all 3 axes were enabled.

Sounds good to me.

> I admit to not knowing the rationale for the query system, and was planning on leaving it stuck to the first y axis at the moment.

> `PixelsToPlot` in this patch uses the axis as currently selected by `SetPlotYAxis`. I haven't yet gotten around to fixing all the APIs, like `GetPlotRange` yet. Do you think it would be useful to be able to switch the queried axis independently of the `SetPlotYAxis` setting?

I do think it might be useful and needed in some scenarios. Again, I'm in favor of just adding an optional variable to specify the y axis of interest to all of these functions. The query system allows the user to draw a query rect on the plot, and then retrieve the plot units associated with the rect with `GetQueryRange`. In the demo, I show using it to compute the mean of a sub-range, or using it to render a zoomed view of a plot. It's meant to be flexible. 
 
> I was planning on having the second and third y axis be hard coded to the right hand side for now. If you have 3 and are rendering the values, it will be cluttered, but if you need 3, then I figure it doesn't matter that much if it is ugly?

I agree. I think the right hand side should be reserved for the auxiliary axes. There are probably ways we can make it pretty, but we can wait until we have a working prototype. 

I'm tied up right now with other projects, so I can't contribute directly. Let me know how I can be useful otherwise. Happy to answer more questions. And of course, feel free to make any changes you think are necessary or required to make this work. 

Cheers!

**Comment by ozlb** [comment]
If you are interested in my opinion, I'm very interested in multiple y-axis and i did some trials as well and i came to max 4 basically because of symmetric distribution 2 on the left side and 2 on the right side of the plot area, while multiple x-axis I ever need it; actually i think that it's interesting to sync x-axis range on multiple plots.

Generally, i think that ibaAnalyzer is handling very well it and you can see in action in following videos. I think that they are very interesting because you can find answers/ideas of above questions.

 [https://www.youtube.com/watch?v=5BvaLGYyy6c&list=PLa_-TZ3jX4Fd80uLaiZOOaVmPBlT6LxbX&index=4](url)

Actually they do not have limits on Y axis and it's handled by drag and drop signals on and out Y axis (merge, join and split signals on same Y axis)

[https://www.youtube.com/watch?v=GSUkIThPiBY&list=PLa_-TZ3jX4Fd80uLaiZOOaVmPBlT6LxbX&index=11](url)

Also in this video you can see in action the merge and how they approach Query by markers (sort of QueryX that we already discuss about) 

[https://www.youtube.com/watch?v=9HWBc_oHB-k](url)

**Comment by ozlb** [comment]
@jpieper 
I know is beta code, but with standard imgui compile flags i prompt following errors.

``` cpp
    auto update_axis_color = [&](auto axis_flag, auto* col) {
        const ImVec4 col_Axis = gp.Style.Colors[axis_flag].w == -1 ? ImGui::GetStyle().Colors[ImGuiCol_Text] * ImVec4(1, 1, 1, 0.25f) : gp.Style.Colors[axis_flag];
        col->Major = GetColorU32(col_Axis);
        col->Minor = GetColorU32(col_Axis * ImVec4(1, 1, 1, 0.25f));
        col->Txt   = GetColorU32({col_Axis.x, col_Axis.y, col_Axis.z, 1});
    };

    update_axis_color(ImPlotCol_XAxis, &gp.Col_X);
    update_axis_color(ImPlotCol_YAxis, &gp.Col_Y[0]);
    update_axis_color(ImPlotCol_Y2Axis, &gp.Col_Y[1]);
    update_axis_color(ImPlotCol_Y3Axis, &gp.Col_Y[2]);
```
![Screenshot 2020-05-10 at 07 39 22](https://user-images.githubusercontent.com/3250876/81491750-f6fe5e00-9291-11ea-9023-8b37aae5d2f8.png)

I actually replaced with "old" style code ...

``` cpp
    const ImVec4 col_Axis_X = gp.Style.Colors[ImPlotCol_XAxis].w == -1 ? ImGui::GetStyle().Colors[ImGuiCol_Text] * ImVec4(1, 1, 1, 0.25f) : gp.Style.Colors[ImPlotCol_XAxis];
    gp.Col_X.Major = GetColorU32(col_Axis_X);
    gp.Col_X.Minor = GetColorU32(col_Axis_X * ImVec4(1, 1, 1, 0.25f));
    gp.Col_X.Txt   = GetColorU32({col_Axis_X.x, col_Axis_X.y, col_Axis_X.z, 1});

    const ImVec4 col_Axis_Y0 = gp.Style.Colors[ImPlotCol_YAxis].w == -1 ? ImGui::GetStyle().Colors[ImGuiCol_Text] * ImVec4(1, 1, 1, 0.25f) : gp.Style.Colors[ImPlotCol_YAxis];
    gp.Col_Y[0].Major = GetColorU32(col_Axis_Y0);
    gp.Col_Y[0].Minor = GetColorU32(col_Axis_Y0 * ImVec4(1, 1, 1, 0.25f));
    gp.Col_Y[0].Txt   = GetColorU32({col_Axis_Y0.x, col_Axis_Y0.y, col_Axis_Y0.z, 1});

    const ImVec4 col_Axis_Y1 = gp.Style.Colors[ImPlotCol_Y2Axis].w == -1 ? ImGui::GetStyle().Colors[ImGuiCol_Text] * ImVec4(1, 1, 1, 0.25f) : gp.Style.Colors[ImPlotCol_Y2Axis];
    gp.Col_Y[1].Major = GetColorU32(col_Axis_Y1);
    gp.Col_Y[1].Minor = GetColorU32(col_Axis_Y1 * ImVec4(1, 1, 1, 0.25f));
    gp.Col_Y[1].Txt   = GetColorU32({col_Axis_Y1.x, col_Axis_Y1.y, col_Axis_Y1.z, 1});

    const ImVec4 col_Axis_Y2 = gp.Style.Colors[ImPlotCol_Y3Axis].w == -1 ? ImGui::GetStyle().Colors[ImGuiCol_Text] * ImVec4(1, 1, 1, 0.25f) : gp.Style.Colors[ImPlotCol_Y3Axis];
    gp.Col_Y[2].Major = GetColorU32(col_Axis_Y2);
    gp.Col_Y[2].Minor = GetColorU32(col_Axis_Y2 * ImVec4(1, 1, 1, 0.25f));
    gp.Col_Y[2].Txt   = GetColorU32({col_Axis_Y2.x, col_Axis_Y2.y, col_Axis_Y2.z, 1});
```

**Comment by jpieper** [comment]
@ozlb Does imgui/imlib have a defined minimum supported set of compilers or versions?  The imgui linux Makefile's at least seem to use whatever random compiler you have installed.  I'm guessing maybe you're assuming no more than C++11?

**Comment by epezent** [comment]
Taken from the ImGui FAQ:

> Dear ImGui takes advantage of a few C++ languages features for convenience but nothing anywhere Boost insanity/quagmire. Dear ImGui does NOT require C++11 so it can be used with most old C++ compilers. Dear ImGui doesn't use any C++ header file. Language-wise, function overloading and default parameters are used to make the API easier to use and code more terse. Doing so I believe the API is sitting on a sweet spot and giving up on those features would make the API more cumbersome. Other features such as namespace, constructors and templates (in the case of the ImVector<> class) are also relied on as a convenience.

In general, I've been avoiding C++11 features, all C++ headers and STL usage, use of `auto`, and inheritance.  Templates are OK apparently.

**Comment by jpieper** [comment]
Sigh.  Alright.  You have a few `auto`s in there.  Guess I can submit patches to remove them.

While we're at it, it looks like you're not using the imgui editorconfig... namely you have a lot of trailing whitespace sprinkled about.  Is that intentional?

**Comment by epezent** [comment]
Thanks, guess I didn't catch them all! White space wasn't intentional, just me being sloppy. Yes, let's tidy it up with their .editorconfig file.

**Comment by jpieper** [comment]
I made a PR to make it easier to get to a diff in github: https://github.com/epezent/implot/pull/24

I think I have everything working except for queries now:

![20200510-multi-y-axis](https://user-images.githubusercontent.com/78958/81505062-d0a0e880-92ba-11ea-99f0-d44116320b69.gif)

If this still looks good, I can do queries.

**Comment by epezent** [comment]
BEAUTIFUL! This already quite polished. Excellent work.

I don't really have major concerns or feedback. It looks like you covered just about everything. I'll give it spin shortly and let you know if anything seems funky.

**Comment by jpieper** [comment]
@ozlb Interestingly, I'm using implot to make an application very similar to ibaAnalyzer:

![20200510-tplot2](https://user-images.githubusercontent.com/78958/81505909-c5e95200-92c0-11ea-9e3a-3298fe1f3613.gif)

Not quite as full featured, but then again it only has two days of effort into it. ;)

**Comment by epezent** [comment]
@jpieper , here's my initial feedback from demo and glancing at the header API changes. I haven't looked at the impl. details yet.

- A simple dividing line between Y2/Y3 would by visually helpful.
- Bug: If drag starts on one axis, and the mouse moves into the hit box of the adjacent axis, then both axes start to drag. The expected behavior is for only the axis that was "mouse downed" to drag. It's also present when moving from an individual axis into the main plot area, so this may have been there all along I just never noticed.
 - The right axes hit box should extend leftward into the plot area by the tick mark size (~5px). This is so that it can still be individually dragged when the labels aren't visible. 
- Y3 tick marks aren't rendering. Is this intentional? I can see what it might be.
- The API is really slick, and still just as simple to use!
- `ImAxisFlags_Auxiliary_Default` ... good call!
- So, `y_axis = -1` will use whatever axis was last set via `SetPlotYAxis` (or 0 if it hasn't been used)? I like it.
- Do you think aux. axes should automatically have a different color than `ImGuiCol_Text`? It would complicate the way axes color works (we'd have to introduce a state variable maintained per axis instead of a global state variable). I don't think it's super necessary, but your opinion matters more.
- Can we format the cursor label to something like: `1.23, 4.56, (7.89), (0.12)`, just to break up the visual clutter a bit.
- The following appear to be working correctly as far as I can tell: lock min/max, invert, log scale, grid lines, labels...as mentioned above, ticks only works for Y2 

@ozlb , I think mutli-y-axis will solve the dilemma we've been in with your plot digital y axis "freezing". We can make them behave as the other plot types (responding to y drag/scroll by default). Then, to achieve the current behavior, you can just plot analogs on axis 1, and digitals on axis 2 (which can optionally be locked). It's a much more flexible system than what I was envisioning before. I think @jpieper was alluding to this, but it just hit me. Doh! 

@jpieper, I'll start looking at the implementation now.

**Comment by epezent** [comment]
- I think the names of `ImPlotBounds` and `ImPlotRange` should be flipped. Consequently, `GetPlotRange` etc. should become `GetPlotBounds` etc. I don't the breaking API change will affect too many people at this point.
- Is `constexpr` a pre C++11 thing? Also, spotted a few `auto`s.
- `struct AxisState` looks like a good generalization. Thanks!
- Making the `Transformers` non-static was the right call and something I was going to do myself. The `Transformer` and `Getter` should be passed by const ref. Not sure why I didn't do this to begin with (granted the inlines probably make it a moot point).
- Everything else seems mostly the same, except for y axis related stuff being iterated as an array. Did I miss anything important?

**Comment by jpieper** [comment]
> @jpieper , here's my initial feedback from demo and glancing at the header API changes. I haven't looked at the impl. details yet.
> 
> * A simple dividing line between Y2/Y3 would by visually helpful.

I'll experiment.  It might be useful to provide a drag target if labels are disabled as well.

> * Bug: If drag starts on one axis, and the mouse moves into the hit box of the adjacent axis, then both axes start to drag. The expected behavior is for only the axis that was "mouse downed" to drag. It's also present when moving from an individual axis into the main plot area, so this may have been there all along I just never noticed.

Yes that behavior has always been present, so I kept it.  Mind if I fix it after?

> * The right axes hit box should extend leftward into the plot area by the tick mark size (~5px). This is so that it can still be individually dragged when the labels aren't visible.

Yes.

> * Y3 tick marks aren't rendering. Is this intentional? I can see what it might be.

It was intentional, as I didn't want to have to figure out a visual style for them, and their use is somewhat niche anyways.  I'll noodle for a bit to see if I can make something that works.

> * The API is really slick, and still just as simple to use!
> * `ImAxisFlags_Auxiliary_Default` ... good call!

Thanks.

> * So, `y_axis = -1` will use whatever axis was last set via `SetPlotYAxis` (or 0 if it hasn't been used)? I like it.

Yes, I will document that.

> * Do you think aux. axes should automatically have a different color than `ImGuiCol_Text`? It would complicate the way axes color works (we'd have to introduce a state variable maintained per axis instead of a global state variable). I don't think it's super necessary, but your opinion matters more.

It might be nice, but I'd be inclined to punt as I don't need it myself and as you mentioned it would be more complicated.

> * Can we format the cursor label to something like: `1.23, 4.56, (7.89), (0.12)`, just to break up the visual clutter a bit.

I'll try out some alternatives.

> * I think the names of `ImPlotBounds` and `ImPlotRange` should be flipped. Consequently, `GetPlotRange` etc. should become `GetPlotBounds` etc. I don't the breaking API change will affect too many people at this point.

Can do.

> * Is `constexpr` a pre C++11 thing? Also, spotted a few `auto`s.

Nope, I was planning on removing the constexpr and will get rid of the `auto`s too.

> * Making the `Transformers` non-static was the right call and something I was going to do myself. The `Transformer` and `Getter` should be passed by const ref. Not sure why I didn't do this to begin with (granted the inlines probably make it a moot point).

Practically, as they currently stand, it will be more efficient in more cases passing the `Transformer`s by value in the current incarnation since there is only an `int` of state.  I can do cref if you really want.  Passing by any type of reference can in some cases force the compiler to actually mark out some space on the stack so that it can take the address of it when that would otherwise not be required.

> * Everything else seems mostly the same, except for y axis related stuff being iterated as an array. Did I miss anything important?

Not that I know of.

**Comment by epezent** [comment]
> I'll experiment. It might be useful to provide a drag target if labels are disabled as well.

Agreed. Adds some real-estate to click.

> Yes that behavior has always been present, so I kept it. Mind if I fix it after?

 Yep, that's fine. I can look after we merge as well if you run out of steam.

> It was intentional, as I didn't want to have to figure out a visual style for them, and their use is somewhat niche anyways. I'll noodle for a bit to see if I can make something that works.

Might be possible to render them onto the dividing line discussed above?

> It might be nice, but I'd be inclined to punt as I don't need it myself and as you mentioned it would be more complicated.

> I'll try out some alternatives.

> Nope, I was planning on removing the constexpr and will get rid of the `auto`s too.

Roger that.

> Practically, as they currently stand, it will be more efficient in more cases passing the `Transformer`s by value in the current incarnation since there is only an `int` of state. I can do cref if you really want. Passing by any type of reference can in some cases force the compiler to actually mark out some space on the stack so that it can take the address of it when that would otherwise not be required.

Noted for the `Transformer`s. I think my ` Getter`s have a few pointers worth of state, so maybe those are worth passing by ref.

**Comment by jpieper** [comment]
Everything but query integration and the 3rd axis rendering changes is pushed to the PR.

**Comment by jpieper** [comment]
I appear to have also broken the ability to have multiple plots in the demo expanded at the same time.  On the list.

**Comment by epezent** [comment]
I think it's just that you used ImVec(-1,-1) for the size.

**Comment by epezent** [comment]
Actually, no. It does seem broken

**Comment by epezent** [comment]
Sorry, I think it is just the ImVec(-1,-1). Seems the ImGui behavior is to fill until the next collapsing header, not the window border like I thought. That was throwing me off. Just make the size ImVec2(-1,300) and I think it's fine.

**Comment by ozlb** [comment]
@jpieper 
> @ozlb Interestingly, I'm using implot to make an application very similar to ibaAnalyzer:

Very nice! I'm glad you know iba and since it's a mature industrial standard a lot of doubts related to plot operability.


@epezent 
> @ozlb , I think mutli-y-axis will solve the dilemma we've been in with your plot digital y axis "freezing". We can make them behave as the other plot types (responding to y drag/scroll by default). Then, to achieve the current behavior, you can just plot analogs on axis 1, and digitals on axis 2 (which can optionally be locked). It's a much more flexible system than what I was envisioning before. I think @jpieper was alluding to this, but it just hit me. Doh!

To be honest I don't like the idea to "loose" one of the y-axis for digital signals, but you guys probably have different overall vision of the final results. Maybe @jpieper that knows iba and knows probably the benefits of not scaled digital signals can explain you better; if not I will close the PR.

**Comment by jpieper** [comment]
@ozlb Actually those two videos you shared and their front web page are the extent of my iba knowledge, so if they aren't representative, then I'm not clued in.  Probably unfortunately, this is the 5th similar-ish application I've had to build in the last 15 years.  My experience is that most of what you need can be done in a few days, and being capable of modifying the application yourself rather than relying on a vendor gets you the rest of the way there.

I don't have a particular opinion regarding the digital plots, although even using one axis for digital values still leaves you with two axes left once you have three total, so you're still better off than no change.

**Comment by jpieper** [comment]
OK  @epezent , I'm not sure what querying semantics make the most sense given your use cases.

The easiest option would be to make all queries behave like the existing `PixelQuery` option.  Callers could request the query results in any axis they want to.

Options for maintaining non-`PixelQuery` after that I think are filled with unsatisfying compromises:
1. The query could be strictly referenced to the first axis.  Any user interactions that solely affected y axes 2 or 3 would leave the query where it was.  Clients could still ask for the query region in terms of those other axes, but that probably wouldn't be all that useful?
2. The query could be set to follow the users panning if the panning was done by clicking in the main grid, but not if the user clicked on one of the specific axis targets or scroll-wheeled over those targets.  That would give a mix of `PixelQuery` and non-`PixelQuery` behavior depending upon how you interacted with it.
3. You could imagine devising a way for the user to select which axis they wanted the query to be associated with, like by pressing down a number key while using the middle mouse button, and then representing that with color.  This would probably not be all that usable, and would also be complex to implement.

Given that I don't forsee myself using the query behavior for a whole lot, my vote would be for just having all queries act as if `PixelQuery` were active, with a second vote for option # 1.

Thoughts?

**Comment by jpieper** [comment]
I guess a fourth option would be to revert to `PixelQuery` only behavior if more than 1 Y axis is configured, but otherwise leave it the same.  I'm not sure that is any better than the other choices.

**Comment by epezent** [comment]
I agree. In hindsight, I think a pixel based query will be sufficient for most folks. Despite it not being the default (an oversight on my part), I think it's probably the most useful, especially for real-time streaming plots. So, let's do away with plot unit based queries for now. Obviously, the flag should be removed.

**Comment by jpieper** [comment]
I think I have all features done, and took a cleanup pass.  PTAL: #25 

![20200510-multi-y-axis-2](https://user-images.githubusercontent.com/78958/81516338-86912480-9305-11ea-9036-c4e98375cb3c.gif)

**Comment by epezent** [comment]
I'm on it.

**Comment by epezent** [comment]
I may be an hour or two. I'm going to rev us up to v0.2 (I think this is a monumental enough change), and start a change log similar to ImGui's.

**Comment by jpieper** [comment]
No worries.  I will be in bed shortly, so will check back tomorrow.

**Comment by ozlb** [comment]
> @ozlb Actually those two videos you shared and their front web page are the extent of my iba knowledge, so if they aren't representative, then I'm not clued in. Probably unfortunately, this is the 5th similar-ish application I've had to build in the last 15 years. My experience is that most of what you need can be done in a few days, and being capable of modifying the application yourself rather than relying on a vendor gets you the rest of the way there.
> 
> I don't have a particular opinion regarding the digital plots, although even using one axis for digital values still leaves you with two axes left once you have three total, so you're still better off than no change.

Ok, thanks for your attention. I got the message.
You are doing a fantastic job.

**Comment by epezent** [comment]
@jpieper, after a few hours of trying to break it in every way possible, I made a few changes and merged your PR to `master`. You can see the changes I made here: https://github.com/epezent/implot/pull/28

Excellent work and much appreciated! The only loose end is that there seemed to be a performance hit in the benchmark FPS (see my comment in the PR above). 

@ozlb, I want test PlotDigital and the new multi-axis together. Give me a few days to see if I can get a prototype working and then we can discuss this further.

**Comment by jpieper** [comment]
@epezent Looks great.  Thanks for taking it over the finish line!

**Comment by ozlb** [comment]
> @ozlb, I want test PlotDigital and the new multi-axis together. Give me a few days to see if I can get a prototype working and then we can discuss this further.

I update PlotDigital according to latest version (PR https://github.com/epezent/implot/pull/15 ). Maybe you can start from this point that handles multiple levels.
There is also my beloved QueryX and even if Query will cover the functionality, for now i will keep it.
![Peek 2020-05-11 14-38](https://user-images.githubusercontent.com/3250876/81562495-3c578400-9395-11ea-8aa0-257cbc9b3539.gif)

**Comment by ozlb** [comment]
@epezent in latest version there is an issue with ImPlotFlags_NoChild. If after ImGui::EndPlot(); you want to add text like in the example below, it will not be visible (I think is under...).
In previous version it was working. I'm using to display query data and i notice immediately.

``` cpp
    if (ImGui::CollapsingHeader("Benchmark")) {
        static const int n_items = 100;
        static BenchmarkItem items[n_items];
        ImGui::BulletText("Make sure VSync is disabled.");
        ImGui::BulletText("%d lines with %d points each @ %.3f FPS.",n_items,1000,ImGui::GetIO().Framerate);
        SetNextPlotLimits(0,1,0,1, ImGuiCond_Always);
        if (ImGui::BeginPlot("##Bench",NULL,NULL,{-1,300},ImPlotFlags_Default | ImPlotFlags_NoChild)) {
            char buff[16];            
            for (int i = 0; i < 100; ++i) {
                sprintf(buff, "item_%d",i);
                ImGui::PushPlotColor(ImPlotCol_Line, items[i].Col);
                ImGui::Plot(buff, items[i].Data, 1000);
                ImGui::PopPlotColor();
            }   
            ImGui::EndPlot();
        }
        ImGui::Text("Test");
    }
```

**Comment by epezent** [comment]
Interesting. The code I would expect to be the culprit remains unchanged:

```cpp
    const ImVec2 frame_size = CalcItemSize(size, 100, 100);
    gp.BB_Frame = ImRect(Window->DC.CursorPos, Window->DC.CursorPos + frame_size);
    ItemSize(gp.BB_Frame);
    if (!ItemAdd(gp.BB_Frame, 0, &gp.BB_Frame)) {
        gp.NextPlotData = ImNextPlotData();
        gp.CurrentPlot = NULL;
        if (!HasFlag(plot.Flags, ImPlotFlags_NoChild))
            ImGui::EndChild();
        return false;
    }
    gp.Hov_Frame = ItemHoverable(gp.BB_Frame, ID);
    RenderFrame(gp.BB_Frame.Min, gp.BB_Frame.Max, gp.Col_Frame, true, Style.FrameRounding);
```

So it must be something else.

**Comment by ozlb** [comment]
> Interesting. The code I would expect to be the culprit remains unchanged:
> So it must be something else.
Without ImPlotFlags_NoChild it works, so i'm pretty sure it's related to this, but where is the issue i don't know. Actually it takes me a while to understand that my issue after merging to v0.2 was related to ImPlotFlags_NoChild

**Comment by epezent** [comment]
There was a clip rect mismatch, which didn't have any effect on plots with a child region. But when the child was removed, the clip rect affects the main window. I fixed it.
