### ISSUE TITLE
Alternate Colours dependent on a third variable with Bar Plots

### ISSUE THREAD

**Issue by peterwilson136** [epezent/implot#201]
Hi again, is there any way to have a bar plot that plots some y values along the x axis, but each individual colour depends on a third set of numbers. For example, a share price, plotting volume against time, can I make the third variable "closes" impact the colour of the individual bars? In this case, if its looping through all the volumes, at index say 3, I need it to check, 
```
if (closes[i-1] >= closes[i]){
    //Change the next individual bar colour to red
}
else{
    //Change the next individual bar colour to green
}
```
Thanks!

**Comment by epezent** [comment]
No. Each call to PlotBars will produce the same colored bars. You'll need to split your data up and make multiple calls. You might also be able to get crafty with PlotHeatmap.

**Comment by peterwilson136** [comment]
Oh, alright. Thanks!
