### ISSUE TITLE
Spacing Y-axis label

### ISSUE THREAD

**Issue by peterwilson136** [epezent/implot#202]
Hi again, I have another question (sorry to bombard). I need to space out 2 different plots (one below another). The Y-axis on one has values such as `40,60,70` and the other has `1e+07, 2e+07` etc. The extra text offsets the plots so when looking at them (one below another), some data points don't correctly line up. I've thought a somewhat fix would be to make a `'\n` in my y_axis title, but that didn't work. Is there any way to align these, or have a set spacing between my Y-axis label so these plots line up? 
Thank you!

**Comment by epezent** [comment]
This is currently being worked on: #144
