### ISSUE TITLE
Flip/Rotate HeatMaps?

### ISSUE THREAD

**Issue by alibeirami** [epezent/implot#207]
Hi,

Is it possible to Rotate PlotHeatMap Result so it flows Up->Down instead of Right->Left?

Thanks for great lib btw.

**Comment by epezent** [comment]
@alibeirami , I assume you found a solution since you closed the issue?

**Comment by alibeirami** [comment]
> 
> 
> @alibeirami , I assume you found a solution since you closed the issue?

Hi epeznt,

The problem originated when I was working with spectrogram demo code in [Implot Demos](https://github.com/epezent/implot_demos), which I wanted to flow like a waterfall, But After some digging I understood that it is not implot that moves the plot but it is in spectrogram.c. I changed  
`
for (int f = 0; f < N_FRQ; ++f)
                m_spectrogram[f*N_BIN+b] = 20*log10f(std::abs(m_fft_out[N_FRQ-1-f]));
`
to
`
for (int f = 1; f <= N_FRQ; ++f)
                m_spectrogram[b*N_FRQ-f] = 20*log10f(std::abs(m_fft_out[N_FRQ-1-f]));
`
in update_spectrogram function and viola, waterfall.

So, I understood that I am stupid and it is not implot's problem and closed the issue.

Thanks for the follow-up and AWSOME! work BTW.

**Comment by epezent** [comment]
You're welcome! Glad to hear someone is enjoying the spectrogram demo.
