### ISSUE TITLE
Sankey diagrams?

### ISSUE THREAD

**Issue by traverseda** [epezent/implot#21]
My favorite type of chart, although I have no idea how one could implement this and it might be out of scope.

Here's some pretty good examples of sankey diagrams: https://www.iea.org/sankey/#?c=World&s=Balance

**Comment by epezent** [comment]
Sankey diagrams are out of scope for the time being. It's a rather niche plot type, and there are a number of other "complex graphs" that would likely preceded it (e.g. flame graphs). I see how they could have some utility for monitoring process flow in real-time, so I won't rule it out just yet! 

One thing we would need for graphs like this is fast polygon triangulation. Are there any good single file implementations out there?

**Comment by traverseda** [comment]
Seems like there are a lot of plot types, do you want an issue per plot type? Flame graphs do seem like they'd be very nice to have.

I don't know of any fast/cheap polygon triangulation libraries. I presume that's something [nanovg](https://github.com/memononen/nanovg) can do, as recommended by mahi-gui.

**Comment by ocornut** [comment]
FYI given the look of sankey diagrams I don't think you'd need a generic solution for triangulation, an adhoc solution may be easier (lots of it seems to be similar to thick lines).

**Comment by epezent** [comment]
In the case of Sankey diagrams, yes that's definitely true. It's just thick lines with an arrow tail/head. I was thinking generally about more complex graph types that we may support down the road. E.g., some of the plots shown here might need generic triangulation:

https://matplotlib.org/gallery/index.html

That said, this is all far into the future. We just need to focus on the basics now.
