### ISSUE TITLE
SampleColormapU32 always uses the current Style Colormap, instead of the cmap argument

### ISSUE THREAD

**Issue by JamAndCheese** [epezent/implot#213]
I apologize I do not know how to refer to individual files or lines with markdown.
However the file is **implot.cpp**, near line **3403**. The line with the fix is shown below, with the buggy line commented out and the fix right below.

    ImU32  SampleColormapU32(float t, ImPlotColormap cmap) {
          ImPlotContext& gp = *GImPlot;
          cmap = cmap == IMPLOT_AUTO ? gp.Style.Colormap : cmap;
          IM_ASSERT_USER_ERROR(cmap >= 0 && cmap < gp.ColormapData.Count, "Invalid colormap index!");
          //    return gp.ColormapData.LerpTable(gp.Style.Colormap,t);
          return gp.ColormapData.LerpTable( cmap, t );
     }

**Comment by epezent** [comment]
Sorry about that. Just pushed a fix.
