### ISSUE TITLE
Move images on plot

### ISSUE THREAD

**Issue by peterwilson136** [epezent/implot#222]
I've got an image working on a plot, and also by the demo, a `DragPoint`. I have it setup currently that when I drag the point, it drags the image too. I want to have it so the point fits the image at each zoom. As of now, a radius of 30 for a circle does not change size relative to the screen. The image, however, does, and because of this, when I zoom in and out, the circle to click on becomes far harder to use as the image is not changing size like the circle is. How can I get the image to behave as the `DragPoint`? I.e. strictly stay the same size relative to the window, not the plot. 

Also, as an extension, i'm not sure if it is possible, but is there a way to have a `DragRect` so my images that are rectangles fit perfectly when clicked on and don't accidently get clicked on from the side where the circle goes past the width of the rectangle. 

Thanks!

**Comment by epezent** [comment]
You'll need to render the image using custom draw commands. See "Custom Rendering" under the demo. Also this similar issue https://github.com/epezent/implot/issues/234
