### ISSUE TITLE
One legend item per group of bars

### ISSUE THREAD

**Issue by rokups** [epezent/implot#224]
We have a plot that displays results of performance tests. Each bar is a distinct performance test execution, however we display these executions by listing their build information in the legend and use per-build-info color. At this point it would be very useful for us to only show two legend items instead of 16, but be able to display all 16 bars per each perf test. We arent that much interested in how each different build performed, but we would like to be able to see if there are any outliers that performed vastly differently. We also have knobs to display averaged data (so two legend entries, two bars per perf test), but that hides any irregularities in test data.

![image](https://user-images.githubusercontent.com/19151258/117270989-70f40380-ae62-11eb-8b84-5b9990be155a.png)

**Comment by epezent** [comment]
Items with the same label name should collapse into a single legend entry. Are you appending any ##Text to these item labels. If not, then this may be a bug.

**Comment by rokups** [comment]
You are right! They actually do collapse and i do have `##xxx` at the end. I added it in order to achieve stable bar colors even after data is reordered. I will think of something. Thank you! 🙏🏻
