### ISSUE TITLE
Fit line to points

### ISSUE THREAD

**Issue by peterwilson136** [epezent/implot#226]
Is it possible to enable drawing a line when you left click on a plot or holding down control while you click to draw a line? If either of those are possible, can it also be possible that if you have a set of points scattered, when you click to draw a line, if your cursor is near a given point, the line latches onto the point as if it snaps to it to connect to it exactly. For example if there are points (0,0) and a point (10,5), when I click to start drawing a line at (0,0), and I move my mouse whilst holding down left click near the (10,5) point, when i release the mouse it sets the line to that point exactly (from 0,0 to 10,5).

Thanks

**Comment by epezent** [comment]
This should be possible with a bit of effort on your end. See the Query demo which adds points when the plot is clicked. This use case is far to specific and out of scope for us to support.
