### ISSUE TITLE
Equal flag and Plot Limits not working together

### ISSUE THREAD

**Issue by peterwilson136** [epezent/implot#227]
Hi again, 

I am trying to make some simulation, where when the user double clicks to resize the plot, the plot fits back to the default range that a ball travels. This may be from 0m to 100m. I also want the plot to be 'equal' so the angles and trajectory of it look realisting. My problem is, however, I need to set the plot's scale to be equal whilst also setting the limits. For example, if a plot's x axis needs to be 100 values wide, and lets say the plots width is 100 pixels and the height is 50, i need the plot's y axis to be 50 values high. This doesn't work, however in this example here:

```
#include <GL/glew.h>

#ifndef GLFW_INCLUDE_NONE
#define GLFW_INCLUDE_NONE // GLFW including OpenGL headers causes ambiguity or multiple definition errors.
#endif // GLFW_INCLUDE_NONE

#include <GLFW/glfw3.h>

#include "ImGui/imgui.h"
#include "ImGui/implot.h"
#include "ImGui/implot_internal.h"
#include "ImGui/imgui_impl_glfw.h"
#include "ImGui/imgui_impl_opengl3.h"

#include <iostream>


static void MainLoop(GLFWwindow* window)
{
    // Start the Dear ImGui frame
    ImGui_ImplOpenGL3_NewFrame();
    ImGui_ImplGlfw_NewFrame();
    ImGui::NewFrame();

    
    ImGui::Begin("Window", (bool*)0, ImGuiWindowFlags_NoBringToFrontOnFocus | ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoResize);

    static bool fitPlot = false;
    static double range = 70;
    static double height = 20;
    if (fitPlot) {
        fitPlot = false;
        std::cout << "Here" << std::endl;
        ImPlot::SetNextPlotLimitsX(0, range, ImGuiCond_Always);
    }

    if (ImPlot::BeginPlot("Sim", "Range (m)", "Height (m)", { -1, -1 }, ImPlotFlags_NoLegend | ImPlotFlags_Equal)) {

        if (ImPlot::BeginItem("Sim"))
        {
            if (ImPlot::FitThisFrame()) {
                fitPlot = true;
            }
        }
        ImPlot::EndPlot();
    }
    ImGui::End();

    // Rendering
    ImGui::Render();
    glClearColor(0.45f, 0.55f, 0.60f, 1.00f);
    glClear(GL_COLOR_BUFFER_BIT);
    ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());

    glfwSwapBuffers(window);
}


int main(int argc, char* argv[])
{
    const char* glslVersion = "#version 460";

    glfwInit();

    // Create window with graphics context
    GLFWwindow* window = glfwCreateWindow(1280, 720, "Program", NULL, NULL);

    glfwMakeContextCurrent(window);
    glfwSwapInterval(0); //  vsync

    //Initialize GLEW + ImGui
    glewInit();

    // Setup Dear ImGui context
    IMGUI_CHECKVERSION();
    ImGui::CreateContext();
    ImPlot::CreateContext();

    // Setup Dear ImGui style 
    ImGui::StyleColorsLight();

    // Setup Platform/Renderer backends
    ImGui_ImplGlfw_InitForOpenGL(window, true);
    ImGui_ImplOpenGL3_Init(glslVersion);


    while (!glfwWindowShouldClose(window))
    {
        //Events
        glfwPollEvents();

        MainLoop(window);
    }

    ImGui_ImplOpenGL3_Shutdown();
    ImGui_ImplGlfw_Shutdown();
    ImPlot::DestroyContext();
    ImGui::DestroyContext();

    glfwDestroyWindow(window);
    glfwTerminate();


    return 0;
}

```

How can I get it so that when the user resizes the plot (double clicks), the plot maintains equal scaling but also sets the limits to what i set it to be?

**Comment by epezent** [comment]
For reasons that not worth the trouble of explaining, we have to constrain the X axis aspect ratio to the Y axis aspect ratio for `ImPlotFlags_Equal`. So, what's happening is you explicitly set the x-limits, but the algorithm resets those values once it determines X's aspect ratio is no longer approximately equal to Y's. 

I've added bit of code to handle the edge case when user's explicitly set the x-limits on a frame. It's not a perfect solution, and you may notice that you range of [0,70] might get nudged a bit on subsequent frames as the constrain converges. 

https://github.com/epezent/implot/commit/3109940b46837d5c71b2d273d585bd21a88e7b81

**Comment by peterwilson136** [comment]
I have tried to play around with the plot dimensions and range, but I can't quite come up with an exact formula for equal scaling based off of its dimentions. I.e, plot dimentions are `{1000, 500}`, if the x-axis should have a max range of `70`,  and the y-axis should have a max range of `20`, ignore the y range (because it would only be 40 if the sizes were equal, still less than 70) and decide to set the limits to `{0, 70, 0, 35}` (35 because it is half the size in the Y as it is in the X (and vice versa if the Y is bigger). This seems like a pretty obvious solution, however I cannot get it to perfectly work given the font sizing affects the dimensions, the magnitude of the value etc. I am hoping that there is just a definitive way to do this as I imagine you would have had to when determining what the scaling is with the `ImPlotFlags_Equal`?

Thanks again for your replies!
