### ISSUE TITLE
Is there a good implot-style source (D3, etc) to template adding additional charts - treemaps, pyramid plots, network graphs, etc?

### ISSUE THREAD

**Issue by dgm3333** [epezent/implot#230]
I'm converting a program from a pure win32 app to imgui, and wondering what the best way to add additional plot types?
eg is implot is templated from some other library which might include these graphs (D3, etc) so I could copy them and ease the process?
[EDIT: I figured out the pyramid plot is created with a horizontal bar plot with shift set to 0 - so have already replicated that]

I'd be happy to share my original cpp code to draw these plots but it's horrible as it's some years old and some of the views are hardcoded and they will need a rewrite to be library friendly

![image](https://user-images.githubusercontent.com/51210/118762621-70019f80-b86e-11eb-97a1-05b631d223b1.png)
![image](https://user-images.githubusercontent.com/51210/118763160-49903400-b86f-11eb-9126-0bbf4e3c7428.png)
![image](https://user-images.githubusercontent.com/51210/118763966-a6d8b500-b870-11eb-8e9c-a5e1cb1e92fd.png)
![image](https://user-images.githubusercontent.com/51210/118764044-c2dc5680-b870-11eb-87d2-d958d04a11bc.png)

**Comment by epezent** [comment]
No, all of implot's code is original, including the rendering code. We calculate triangles for plots and send them through ImGui's draw list API. 

Take a look inside of implot_items.cpp. I think you'll find a few good examples of the pipeline we have setup. Happy to consider any PRs for new plot types.

**Comment by epezent** [comment]
With the exception of the first plot type you show, I think most of these would be easier to realize as their own ImGUi widget since they don't require Cartesian coordinates and many of the features that ImPlot has.
