### ISSUE TITLE
Lock the pixel:data scaling ratio to whole number values to minimise antialiasing artifacts?

### ISSUE THREAD

**Issue by dgm3333** [epezent/implot#232]
I'm trying to graph long timespan data series with data for every day over 10+ years.
Thus I want to maintain the ability to zoom and view macro or fine detail.
However when zooming or resizing the window with 10% steps then the scaling causes localised blocks of data to be masked or emphasised relative to other portions of the time series purely due to anti-aliasing.
I would like to be able to step the zoom in whole number ratios to stop this happening
eg 3:1, 2:1, 1:1 1:2, 1:3, etc

I normally like IMPLOT_ZOOM_RATE = 0.1, so I'd like this to be able to be restricted to only certain graphs
I've tried (without resolving the issue):
-setting IMPLOT_ZOOM_RATE to 0.5 or 1.0 and 
-locking aspect ratio to an int: plot.XAxis.SetAspect((int)plot.YAxis[0].GetAspect());
I'm presuming I will have to edit the SCROLL INPUT code (near float zoom_rate = IMPLOT_ZOOM_RATE;) and ensure SetAspect is called with a whole number ratio, but I'm not sure why the (int) test didn't work?
Thanks

This is what I want to avoid:-
![image](https://user-images.githubusercontent.com/51210/119220486-b2331700-bae2-11eb-94ce-cf9a67bc0faf.png)

**Comment by epezent** [comment]
I don't quite understand your issue. A video or GIF would be helpful. Regardless, it sounds like you're going to require a custom zoom policy. We don't currently enable overriding input behavior, but it's been requested a few times and is on my radar.

**Comment by dgm3333** [comment]
This is an example video of zooming in on the above data set - depending on the zoom the view changes dramatically and frequently distorts the information. I can display monthly, weekly or daily values depending on the zoom level, but when a day or week crosses pixel boundaries the anti-aliasing causes some regions to be inappropriately darker than others - and for some data sets I've seen 100+ pixel blocks be almost totally faded out of the render.


https://user-images.githubusercontent.com/51210/119389592-c08c5900-bcc3-11eb-8491-1a4d40acd6ee.mp4

**Comment by epezent** [comment]
Yea, that looks pretty bad. Quite frankly, I'm not sure there's much we can do to make it any better -- at the end of the day, all we do is send triangles to ImGui which sends them off to your rendering backend. Perhaps there are some platform settings you can enable to mitigate the artifacts? Sorry, I'm not an expert here.

I'm not convinced that setting the zoom level to whole number ratios will have any effect here...have you experiment with this yet? Also, have you attempted to render this plot in another plotting library (MATLAB/matplotlib)? I'm curious how it looks in those libraries at the macro zoom level. 

If you can provide the data set and rendering code, I might be able to provide more insight after playing around with it.

**Comment by dgm3333** [comment]
I think this is probably not worth your effort to try and sort at the implot level as there are alternative (probably better) ways of avoiding the artifacts.
I ultimately ended up just hiding the bars by default and displaying a 30 day running average - this provides a good overview at large scale and if you really need the detail at high zoom you can just switch the bars on (BTW you have really made a superb library - even down to being able to click the legend to show or hide series).
The option to just calculate averages over different timescales (daily, 2-daily, 4-daily, weekly, monthly), then display them dependent on the zoom (just as the graph changes x-axis labels) was still not a clear visualisation (although zoom was better).

Before trying that I did try modifying implot.cpp to lock the zoom ratio to whole numbers but you're right it didn't help nor did my tinkering with various other zoom settings.
Also in reality the number of datasets which have a decade of daily data are going to be fairly limited

However since you asked, here is a function which produces the same effect (without the large dataset).

```
#include <stdlib.h>
void drawZoomGlitch(globalSettings& gS, allData& aD) {
	constexpr int32_t UNIXTP2015 = 1420062840;
	constexpr int32_t UNIXTP2020 = 1577847600;
	constexpr int32_t SECONDSPERDAY = 86400;

	static uint16_t dataPoints = (UNIXTP2020 - UNIXTP2015)/SECONDSPERDAY + 1;
	static int32_t* totalPerDay{ new int32_t[dataPoints] {0} };
	static int32_t* unixTPSeries{ new int32_t[dataPoints] {0} };

	static double graphYMax = 0;
	static bool arraysEmpty = true;
	if (arraysEmpty) {
		arraysEmpty = false;
		for (uint16_t day = 0; day < dataPoints; day++) {
			unixTPSeries[day] = UNIXTP2015 + day * SECONDSPERDAY;
			if (day % 6 == 0 or day % 7 == 0) {
				totalPerDay[day] = rand() % 20;
			} else {
				totalPerDay[day] = 100 + rand() % 100;
			}
			if (graphYMax < totalPerDay[day])
				graphYMax = totalPerDay[day];
		}
	}

	ImPlot::SetNextPlotLimitsX((double)UNIXTP2015, (double)gS.curClock, ImGuiCond_Once);
	ImPlot::SetNextPlotLimitsY((double)0.0, (double)graphYMax, ImGuiCond_Always);

	//ImPlot::GetStyle().UseLocalTime = true;   // this doesn't affect date rendering :-(
	static ImPlotAxisFlags xflags = ImPlotAxisFlags_Time;
	static ImPlotAxisFlags yflags = ImPlotAxisFlags_AutoFit | ImPlotAxisFlags_RangeFit;
	if (ImPlot::BeginPlot("Bad Zoom", "Date", "RandomData", ImVec2(-1, -1), 0, xflags, yflags))
	{
		ImPlot::PlotBars("Rand Per Day", unixTPSeries, totalPerDay, dataPoints-1, (double)SECONDSPERDAY);
		ImPlot::EndPlot();
	}

	return;
}
```
