### ISSUE TITLE
How can I plot images as markers with constant size?

### ISSUE THREAD

**Issue by dgm3333** [epezent/implot#234]
I thought it would be very easy to plot images as markers in a series, but I'm struggling with the scaling (and I can't figure out how to add it to the legend - but that's less important).

I know my image is 32x32, so I would have thought I would be able to use PixelsToPlot to get the correct scaling, but the image is badly stretched and when zooming in or out it flips around (at least in my function with a unix time series x-axis, although not in the implot_demo version).
This is the basic implot_demo - which I would have expected would scale the font texture to 32x32 pixels irrespective of the axis zoom, but it doesn't
```
        if (ImPlot::BeginPlot("##image2")) {
            static ImPlotPoint i2p = ImPlot::PixelsToPlot(16, 16);
            static ImPlotPoint bmid(0.5, 0.5);
            static ImPlotPoint bmin0 = { bmid.x - i2p.x, bmid.y - i2p.y };
            static ImPlotPoint bmax0 = { bmid.x + i2p.x, bmid.y + i2p.y };
            ImPlot::PlotImage("my image", ImGui::GetIO().Fonts->TexID, bmin0, bmax0, uv0, uv1, tint);
            ImPlot::EndPlot();
        }
```

This is my series plotter - which is intended to do the same thing (but for a series)...
```
struct imageContainer {
    int w = 0;
    int h = 0;
    GLuint texture = 0;
};
void plotImageSeries(imageContainer curImg, double *x, double *y, uint16_t size) {
    for (uint16_t iCnt = 0; iCnt < size; iCnt++) {
        ImPlotPoint i2p = ImPlot::PixelsToPlot(curImg.w/2, curImg.h/2);
        ImPlotPoint bmin = { *(x + iCnt) - i2p.x, *(y + iCnt) - i2p.y };
        ImPlotPoint bmax = { *(x + iCnt) + i2p.y, *(y + iCnt) + i2p.y };
        std::cout << (uint64_t)i2p.x << "," << i2p.y << " (" << (uint64_t)bmin.x << "," << bmin.y << ")-(" << (uint64_t)bmin.x << "," << bmin.y << ")" << std::endl;
        ImPlot::PlotImage("", (void*)(intptr_t)curImg.texture, bmin, bmax);
    }
}
```

**Comment by epezent** [comment]
@dgm3333, you might be better off writing a custom plotter for this. Use `GetPlotDrawList()->AddImage()` between a `PushPlotDrawList` and `PopPlotDrawList`. Compute the center pixel position with `PlotToPixels`, then offset by 16 pix for the min and max positions.

See 'Custom Rendering' in the demo for an example.

**Comment by dgm3333** [comment]
Thanks thats exactly what I was after
```
void plotImageSeries(imageContainer& curImg, double *x, double *y, uint16_t size) {
    for (uint16_t iCnt = 0; iCnt < size; iCnt++) {
        ImPlotPoint c = ImPlot::PlotToPixels(ImPlotPoint(x[iCnt], y[iCnt]));
        ImPlot::PushPlotClipRect();
        ImPlot::GetPlotDrawList()->AddImage((void*)curImg.texture,
            ImVec2(c.x - (float)curImg.w/2, c.y - (float)curImg.h/2),        // top left
            ImVec2(c.x + (float)curImg.w/2, c.y + (float)curImg.h/2));     // bottom right
        ImPlot::PopPlotClipRect();
    }
}
```
