### ISSUE TITLE
Data at max edge is not plotted when ImPlotAxisFlags_AutoFit is used?

### ISSUE THREAD

**Issue by YojiroAstom** [epezent/implot#236]
Hi, 

I'm experimenting with ScatterPlot.
When using AutoFit feature on X or Y axis, new data at max edge is not shown,
or at least it looks like AutoFit flag is causing the data not visible on plot.
On the other hand, data at lower edge is shown.

Is this supposed behavior?

It might simply taking max of range inclusively should change the situation.
Thank you.

**Comment by epezent** [comment]
Thanks for bringing this to my attention. This was indeed the issue as `ImRect::Contains` was not checking the max inclusively, to my surprise. The issue should be resolved. Let me know if it is not.

**Comment by YojiroAstom** [comment]
yes, it is fixed indeed with my sample project.
thank you.
