### ISSUE TITLE
Issue with rendering large number of points with PlotScatter

### ISSUE THREAD

**Issue by WeirdRubberDuck** [epezent/implot#237]
First of all, awesome library! Been playing around with it a bit for a project and am very excited about it

I'm however experiencing issues rendering a large number of points (> 3250 ish) using PlotScatter and it's proving to be quite troublesome. See video for example. The input controls the `count` passed to the function: `ImPlot::PlotScatter("Label id", xs, ys, count);`. If fewer than 3250-ish points are in view (at least that's my guess), the rendering issues disappear, as shown at the end of the video. 

Is this a known issue? If, so, are there any workarounds? If not, I hope you find this useful. 

I'm using the version tagged "ImPlot v0.9 WIP"

https://user-images.githubusercontent.com/8808894/120482114-17bfb700-c3b1-11eb-8adf-c504bae17b88.mov

**Comment by marcizhu** [comment]
From the [README](https://github.com/epezent/implot/blob/master/README.md#special-notes):
> If you experience data truncation and/or visual glitches, it is **HIGHLY** recommended that you EITHER:
> 1) Handle the `ImGuiBackendFlags_RendererHasVtxOffset` flag in your renderer when using 16-bit indices (the official OpenGL3 renderer supports this) and use an ImGui version with patch [imgui@f6120f8](https://github.com/ocornut/imgui/commit/f6120f8e16eefcdb37b63974e6915a3dd35414be), OR...
> 2) Enable 32-bit indices by uncommenting `#define ImDrawIdx unsigned int` in your ImGui `imconfig.h` file.

Have you tried this? I think it might be the cause of those glitches.

**Comment by epezent** [comment]
Thanks @marcizhu. Yes, this is probably your issue. Let us know if it's not, otherwise please close the issue. Thanks, and happy to hear you are enjoying the library!

**Comment by WeirdRubberDuck** [comment]
Ah, apparently missed that part of the readme. That was indeed the problem, thank you!
