### ISSUE TITLE
ImPlotAxisFlag_RangeFit without entire plot fit

### ISSUE THREAD

**Issue by peterwilson136** [epezent/implot#238]
Hello again,

I am wondering if it is possible to have a plot fit the limits to a percentage of the room for the plot. I.e. currently the flag ensures that each point is exactly fit to the limits of the plot on the screen, however I am trying to have some white space / padding from this so a line plot (for example) may have +/- 5% padding between the edges of the points and the limits of the plot.

Thanks!

**Comment by epezent** [comment]
See `ImPlotStyleVar_FitPadding`
