### ISSUE TITLE
GetColormapSize returns wrong value

### ISSUE THREAD

**Issue by jvannugteren** [epezent/implot#241]
Hi Epezent,

I'm still using your library almost every day. I found the following tiny issue. 
```
ImPlot::GetColormapSize(ImPlot::GetColormapIndex("Greys"));
```
Returns a value of 10, while the Greys colormap has only two entries. The same happens with my custom user supplied colormaps.

Secondly. Is there a way to reverse the colormaps? I found `bool reversed` in RenderColorBar but I think it is not exposed to the user.  For me it would already be sufficient if I could reverse the ColormapScale. 

Thanks.

**Comment by epezent** [comment]
Hey @jvannugteren! Looks like the function `GetColormapSize` was ignoring the value passed to it and always defaulting to the current colormap. I've pushed a fix. 

Regarding reversing colormaps, I would advise having two separate maps: `MyColormap` and `MyColormap_Reversed`. Not the most elegant solution, but certainly the easiest at the moment. Adding support for reverse indexing maps will just add unnecessary overhead, especially for heatmaps which may sample colormaps thousands of times per frame. 

When you say that you want to reverse the ColormapScale, do you want to invert the gradient AND the axis values, or JUST the gradient?

**Comment by jvannugteren** [comment]
Thank you, the `GetColormapSize` works fine now. I wanted to create a button "reverse colormap". I was planning to invert JUST the gradient on the ColormapScale and do a manual inversion on the input values for the heatmap (and 3D plots). My heatmaps are usually quite static so I can do this operation only once. But I think I can just go with your solution of making two separate maps and then do some logic that determines which map to pick based on whether "reverse" is activated.
