### ISSUE TITLE
Set single plot limit

### ISSUE THREAD

**Issue by peterwilson136** [epezent/implot#243]
Hello again, 

Upon using `FitPadding.y` on some range of values, the set of data I have can never go below zero, but from the large range of data and `FitPadding.y = 0.4f;`, the plot limits range below zero. To fix this, I tried `ImPlot::SetNextPlotLimitsY()`, however it requires `ymax` as well, which I would want to instead set the `ymin` to `0` and then the plot scale accordingly with that limit in mind (or just have a plot min for any zooming or moving of the plot`

Thanks again!

**Comment by epezent** [comment]
I think what you actually want is to enable `ImPlotAxisFlags_LockMin`. This will prevent the fit operation from resetting the y-min value below 0. I won't be adding support to set single plot limits at this time.
