### ISSUE TITLE
Multicolor Plot Shaded 

### ISSUE THREAD

**Issue by Davido71** [epezent/implot#247]
I have been using your plot library quite a lot lately and I'm hoping you can give me some direction on my latest issue.

I'm trying to use PlotShaded() to render different colors when the lines intersect. For example green when line 1 is above line 2 and red when line 1 is below line 2. Is there a way to do this? 

Here is what I have so far:

```
static ImPlotPoint zeroLine(void* data, int i)
{
    return ImPlotPoint(i, 0);
}

static ImPlotPoint getDataSet(void* data, int i)
{
    dataset_t* ptr = reinterpret_cast<dataset_t*>(data);
    return ImPlotPoint(i, ptr->at(i));
}

ImPlot::SetNextFillStyle(ImVec4(0.0f, 0.8f, 0.0f, 1.0f));
ImPlot::PlotShadedG("##wt1", getDataSet, const_cast<dataset_t*>(&data.wt1), zeroLine, nullptr, static_cast<int>(data.wt1.size()), 0.0);
```

I filled in the lower area red to show what I'm trying to do:

![AreaPlotExample](https://user-images.githubusercontent.com/61202402/121790502-2ec68c00-cb9d-11eb-99b9-2afc0dedc6e8.jpg)

**Comment by epezent** [comment]
@Davido71 , take a look at this PR and let me know if it meets your needs: https://github.com/epezent/implot/pull/161

**Comment by Davido71** [comment]
Yes, that points me in the right direction.  Thanks!
