### ISSUE TITLE
Building implot in Visual Studio 2019 breaks zoom and panning and show/hide plot buttons

### ISSUE THREAD

**Issue by parallelno** [epezent/implot#249]
I cloned the latest imgui, opened imgui_examples.sln in Visual Studio 2019. It suggested updating the solution and all of the projects. I did it.
![implot_update](https://user-images.githubusercontent.com/1479747/121819948-cf23bb80-cc44-11eb-8a4a-2fb0b042391f.jpg)
I cloned the latest implot into the folder ..\examples\example_glfw_opengl3\implot 
I changed an example ..\examples\example_glfw_opengl3\main.cpp
After these lines of the code:
#include "imgui.h"
#include "imgui_impl_glfw.h"
#include "imgui_impl_opengl3.h"
#include <stdio.h>
I added a line: 
#include "implot/implot.h" 
and after this line:
        if (show_demo_window)
            ImGui::ShowDemoWindow(&show_demo_window);
I added a call of the implot demo:
        ImGui::Begin("ImPlot");
        ImPlot::CreateContext();
        static bool showIplotDemo = false;
        ImPlot::ShowDemoWindow(&showIplotDemo);
        ImPlot::DestroyContext();
        ImGui::End();

Visual Studio 2019 built the project with no errors, but some of the options don't work, like zoom and panning. I used a mouse wheel to zoom in/out, and mouse buttons to pan the plot area. It has no effect. I recorded gif to show the issue.
![implot_zoom_panning_issue](https://user-images.githubusercontent.com/1479747/121820685-1613b000-cc49-11eb-96be-15e02c053f6e.gif)

I even tried to clone 3 month old version of imgui and implot. same issue. I cloned mahilab/mahi-gui and it builds and works well. A web version works well as well. Could anyone help me to build a working well version of implot examples with VS2019? 

Thank you in advance!

**Comment by epezent** [comment]
You're creating and destroying the implot context in your update loop every frame. I'm surprised it works at all. 

You need to call these functions where imgui is initialized and destroyed at app startup and shutdown. Take another look at the README.

**Comment by parallelno** [comment]
I helped out! thank you so much, Evan!
