### ISSUE TITLE
Copy Paste code error?

### ISSUE THREAD

**Issue by toxieainc** [epezent/implot#252]
https://github.com/epezent/implot/blob/master/implot.cpp#L1993  xt->Major ? plot.XAxis.ColorTxt : plot.XAxis.ColorTxt
https://github.com/epezent/implot/blob/master/implot.cpp#L2003  yt->Major ? plot.YAxis[i].ColorTxt : plot.YAxis[i].ColorTxt

Both times the same variable is used in the selector.

**Comment by epezent** [comment]
Ha, yea seems like a copy paste oversight. I'll fix this. Great catch!
