### ISSUE TITLE
Alternate PlotToPixels function

### ISSUE THREAD

**Issue by peterwilson136** [epezent/implot#259]
Hello again,
I apologise if this is the wrong place for me to post this, I am just a bit confused by a specific comment/function.

When I need to use the `ImDrawList` for drawing circles and such on a plot, I need to call this function (`PlotToPixels`) to get the pixel location, invariant of the plot scale. There is a comment above its implementation that I am a bit confused by,
`// This function is convenient but should not be used to process a high volume of points. Use the Transformer structs below instead.` and I was hoping you could point me into the direction/usage of the alternatives since I can't quite find out where/what the alternate Transformer structs are. 

Thanks!

**Comment by epezent** [comment]
Some things got shifted around and that comment is now out of context. The Transformer structs are in implot_items.cpp now and are an implementation detail. 

The purpose of these structs is to process a high volume of points while minimizing branching. As you can see in PlotToPixels, each conversion needs to check against the current axis scaling (linear or log). With the Transformer structs we do so before using them. See usage examples in the same file.
