### ISSUE TITLE
SetNextPlotLimitsY doesn't change if called again with different value

### ISSUE THREAD

**Issue by t0mke** [epezent/implot#275]
I have 2 scrolling plots that can be viewed when activating its radio button (only one of them can be drawn)

Because one of the plots has a different value range, I have to change the y plot limit in order to fit the full graph. What ends up happening is I only get the plot limit that of the first plot which was drawn, so it's like it never registers the SetNextPlotLimitsY statement.

here's my code
`			

                    ImGui::Begin("Graph Window", &show_graph_window);
			static ScrollingBuffer sdata[32];
			static ScrollingBuffer sdata2[32];
			static float history = 1000;
			static int r = 0;
			ImGui::Text("");
			ImGui::RadioButton("plot 1", &r, 0); ImGui::SameLine();
			ImGui::RadioButton("plot 2", &r, 1); ImGui::SameLine();
			ImGui::SetNextItemWidth(-60);
			ImGui::SliderFloat("History", &history, 1, 1000, "%.1f s");
			static ImPlotAxisFlags flags = ImPlotAxisFlags_NoTickLabels;

			int i = 0;
			sdata[i].AddPoint((float)tick, 100.0f);
			sdata2[i].AddPoint((float)tick, 4.0f);

			ImPlot::SetNextPlotLimitsX((double)tick - (double)history, tick, ImGuiCond_Always);
			snprintf(buffer, 99, "##Scrolling %d", i);
			if (!r) {
				ImPlot::SetNextPlotLimitsY(-100, 1000);
				if (ImPlot::BeginPlot(buffer, NULL, NULL, ImVec2(175, 175), ImPlotFlags_AntiAliased, flags, flags)) {
					ImPlot::PlotLine("", &sdata[i].Data[0].x, &sdata[i].Data[0].y, sdata[i].Data.size(), sdata[i].Offset, 8);
					ImPlot::EndPlot();
				}
			}
			else {
				ImPlot::SetNextPlotLimitsY(0, 10);
				if (ImPlot::BeginPlot(buffer, NULL, NULL, ImVec2(175, 175), ImPlotFlags_AntiAliased, flags, flags)) {
					ImPlot::PlotLine("", &sdata2[i].Data[0].x, &sdata2[i].Data[0].y, sdata2[i].Data.size(), sdata2[i].Offset, 8);
					ImPlot::EndPlot();
				}
			}
			ImGui::End();`

**Comment by epezent** [comment]
What happens if you pass `ImGuiCond_Always` to `SetNextPlotLimtisY`?

**Comment by t0mke** [comment]
> What happens if you pass `ImGuiCond_Always` to `SetNextPlotLimtisY`?

thanks, it works fine now.
