### ISSUE TITLE
Option to skip nan values in PlotLine

### ISSUE THREAD

**Issue by kv-gits** [epezent/implot#276]
Implemented this by adding new Item "LineTo" with simple check for nan, but may be flag for common PlotLine would be more useful?

Also used "cmath" header file. Not sure is it propper for implot architecture.

```
template <typename Getter, typename Transformer>
inline void RenderLineToStrip(const Getter &getter, const Transformer &transformer, ImDrawList &DrawList, float line_weight, ImU32 col) {
    ImPlotContext &gp = *GImPlot;

    if (ImHasFlag(gp.CurrentPlot->Flags, ImPlotFlags_AntiAliased) || gp.Style.AntiAliasedLines) {
        ImVec2 p1 = transformer(getter(0));

        for (int i = 1; i < getter.Count; ++i) {
            ImVec2 p2 = transformer(getter(i));

            if (gp.CurrentPlot->PlotRect.Overlaps(ImRect(ImMin(p1, p2), ImMax(p1, p2))))
                DrawList.AddLine(p1, p2, col, line_weight);

            if (std::isnan(p2.y) == false) p1 = p2;
        }
    } else {
        RenderPrimitives(LineToStripRenderer<Getter, Transformer>(getter, transformer, col, line_weight), DrawList, gp.CurrentPlot->PlotRect);
    }
}
```

**Comment by epezent** [comment]
I suspect this check has some non-trivial overhead, and we would want users to be able to opt in to it only if they need it. At some point in the near future, I want to add `ImPlotLineFlags`, etc. and so we could enable this with e.g. `ImPlotLineFlags_SkipNan`. It will be a while before I get to this, though.

**Comment by pakali** [comment]
Let's discuss this a little bit, skipping values in chart will be very helpful, but it should also be applied to axis X sometimes (like time series data), so such flag I don't think will help enough to cover this case.
I thinking about some additional function like:

```
SubplotBegin(..)
SubplotSkip(0,1000)
SubplotSkip(2000,3000)
....
SubplotEnd()
```

**Comment by epezent** [comment]
This is now possible with `ImPlotLineFlags_SkipNaN`:

![image](https://user-images.githubusercontent.com/29577475/174466330-b04fc22d-5e51-41e7-a76e-44c0bac77499.png)

![image](https://user-images.githubusercontent.com/29577475/174466339-344298ca-863b-4938-9851-c51b4024488f.png)
