### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by hdclark** [epezent/implot#284]
Just wanted to let the contributors know how much I appreciate implot.
I use it for real-time plotting within a medical image analysis program (hdclark/DICOMautomaton), and everything just works.
Implot is really fantastic. Thank you!

**Comment by epezent** [comment]
Hi there! Thank you for the feedback! I'm happy to hear that your are enjoying the library. We strive hard for "just working". Feel free to post some screenshots over over in #180 -- we'd love to see your project :) 

PS -- I'm interested in hearing suggestions on how to make ImPlot more useful for medical imaging, if you have any (e.g. better heatmap/image support, contour plots, etc.)
