### ISSUE TITLE
c++ implot candlestick render

### ISSUE THREAD

**Issue by zabkoo** [epezent/implot#287]
Hello, im creating chart with plotcandlestick but i dont know how to render chart with data from API, because i need to convert string to double and everytime when candle close, move position in array. If candle is opened still insert data to same position `double array[0] = {data1}` and if candle close move position `array[1] = {data1, data2}` and this whole process will run to infinity so chart will have history. I hope you understand me.

```
// Data from API
{
  "o": "0.0010",  // Open price
  "c": "0.0020",  // Close price
  "h": "0.0025",  // High price
  "l": "0.0015",  // Low price
  "x": false,     // Is candle closed?
}
```

```
// Reading data from API and converting to double
std::string s = pt.get<std::string>("letter");
double d = boost::lexical_cast<double>(s);
```

**Comment by epezent** [comment]
I suggest you use a [JSON parser](https://github.com/nlohmann/json) to process your data, and modify the PlotCandlestick example source code to work on an array of OHLC structs instead of multiple arrays.
