### ISSUE TITLE
Stacked bars

### ISSUE THREAD

**Issue by stijnherfst** [epezent/implot#288]
Hi, I've searched around a bit, but couldn't discover whether ImPlot supports stacked bar graphs such as:
![image](https://user-images.githubusercontent.com/8471644/134037844-5d19fcae-bab3-462f-bc43-ed1b5dce476e.png)
I want to plot the frametime composition of my app.

**Comment by epezent** [comment]
Stacked bar charts are not currently implemented, but I'd like to support them eventually. Not hard, just low priority for me right now. Would be happy to review a PR that adds them!

**Comment by dongqiceo** [comment]
I draw your own one

**Comment by epezent** [comment]
Stacked bars are now included in the API:

```cpp
// Flags for ImPlot::PlotBarGroups
enum ImPlotBarGroupsFlags_ {
    ImPlotBarGroupsFlags_None     = 0,      // default
    ImPlotBarGroupsFlags_Stacked  = 1 << 0, // items in a group will be stacked on top of each other
};

// Plots a group of vertical bars. #values is a row-major matrix with #item_count rows and #group_count cols. #label_ids should have #item_count elements.
void PlotBarGroups(const char* const label_ids[], const T* values, int item_count, int group_count, double group_width=0.67, double x0=0, ImPlotBarGroupsFlags flags=ImPlotBarGroupsFlags_None);

// Plots a group of horizontal bars. #values is a row-major matrix with #item_count rows and #group_count cols. #label_ids should have #item_count elements.
void PlotBarGroupsH(const char* const label_ids[], const T* values, int item_count, int group_count, double group_height=0.67, double y0=0, ImPlotBarGroupsFlags flags=ImPlotBarGroupsFlags_None);
```

![image](https://user-images.githubusercontent.com/29577475/151712784-27329017-b885-4574-826d-f3f8699f73c5.png)

![image](https://user-images.githubusercontent.com/29577475/151712800-a996e08f-0305-4a2a-9249-d5186d3dfb6d.png)
