### ISSUE TITLE
trivial build fix (cmath for isnan)

### ISSUE THREAD

**Issue by prlw1** [epezent/implot#309]
I found I needed
```
diff --git a/implot_internal.h b/implot_internal.h
index 2ebe6a3..8b6324d 100644
--- a/implot_internal.h
+++ b/implot_internal.h
@@ -35,6 +35,7 @@
 #define IMGUI_DEFINE_MATH_OPERATORS
 #endif
 
+#include <cmath>
 #include <time.h>
 #include "imgui_internal.h"
 
@@ -121,9 +122,9 @@ static inline T ImRemap01(T x, T x0, T x1) { return (x - x0) / (x1 - x0); }
 // Returns always positive modulo (assumes r != 0)
 static inline int ImPosMod(int l, int r) { return (l % r + r) % r; }
 // Returns true if val is NAN or INFINITY
-static inline bool ImNanOrInf(double val) { return val == HUGE_VAL || val == -HUGE_VAL || isnan(val); }
+static inline bool ImNanOrInf(double val) { return val == HUGE_VAL || val == -HUGE_VAL || std::isnan(val); }
 // Turns NANs to 0s
-static inline double ImConstrainNan(double val) { return isnan(val) ? 0 : val; }
+static inline double ImConstrainNan(double val) { return std::isnan(val) ? 0 : val; }
 // Turns infinity to floating point maximums
 static inline double ImConstrainInf(double val) { return val == HUGE_VAL ?  DBL_MAX : val == -HUGE_VAL ? - DBL_MAX : val; }
 // Turns numbers less than or equal to 0 to 0.001 (sort of arbitrary, is there a better way?)
```
(gcc 10.3.0 -std=c++20)

**Comment by epezent** [comment]
Hi, the `isnan` macro should be provided by `math.h` which we get by including `imgui_internal.h`.  [However, it seems that including `<cmath>` will hide the macro](https://stackoverflow.com/questions/39130040/cmath-hides-isnan-in-math-h-in-c14-c11). Did you by chance include `<cmath>` for some unreleated modifications and then notice the error, or do you also get the error with a vanilla copy of `implot_internal.h`?

**Comment by iTrooz** [comment]
Assuming that the external code can't be modified (ensuring I never included <cmath> anywhere is tedious), what would be the right way to solve this problem ?

How about adding
```cpp
#if not defined(isnan) and __cplusplus
using std::isnan;
#endif
``` 

to implot_internal.h ?

**Comment by prlw1** [comment]
@iTrooz: That is what puzzled me in the first place: in your snippet, `__cplusplus` has to be defined as implot is a C++ library.  I now see that keeping the C `math.h` instead of the C++ `cmath` header is probably just to support pre-C++11 which didn't have `std::isnan` yet. I don't see any minimum version requirements in imgui, so fair enough!

Your patch would cover the
```
// Get rid of those macros defined in <math.h> in lieu of real functions.
```
in `<cmath>`. Amusingly there is a `c_compatibility/math.h` in `gcc/libstdc++-v3` which basically does exactly that.

@epezent: As to the first question, as I wrote, I was using C++20. I obviously did some mathematics to have something to plot, so in my code I included `<cmath>` for the mathematical functions, and `<implot.h>` to plot the results, but got the build error.

This was over 2 years ago. Handwavily, I should check, but I don't remember seeing this problem recently, imgui and implot haven't really changed in this respect, but the thing which changed at my end is that I no longer use gcc10, but gcc12 or above, but there too, I don't really see an obvious change.

**Comment by prlw1** [comment]
Looking at that `c_compatibility/math.h` further, it may just be that the newer `gcc` did change something - see the commit message:  https://github.com/gcc-mirror/gcc/commit/1f378f6dd33ad5067a437d1c456979f8662020d6 (I mainly use not yet released gcc 14 these days)

**Comment by iTrooz** [comment]
> as implot is a C++ library

oh, indeed. I thought it was a C library since cmath wasn't used, which is why I made my patch that way

>  I now see that keeping the C math.h instead of the C++ cmath header is probably just to support pre-C++11 which didn't have std::isnan yet

I'd love to have a confirmation from a maintainer for this: maybe we don't even need #ifdef stuff and can simply use cmath

> in <cmath>. Amusingly there is a c_compatibility/math.h in gcc/libstdc++-v3 which basically does exactly that.

That would explain why that bug only occurred to me when I tried to compile with clang a project normally using gcc
