### ISSUE TITLE
Plots enabled/disabled through Legend

### ISSUE THREAD

**Issue by dsantxez** [epezent/implot#311]
First of all thank you for the great library for plotting.

I have been testing the legend option inside ImPlot and I have seen that it comes with a enabled option to disable/enable painting different plots (Lines, shaded, etc.) in a BeginPlot/EndPlot.

Is there a way to disable that option? I have seen the option of altLegend function inside the implot_internal. I could use this function but I haven't seen a way of disabling the context menu of the Plot or changing for a custom one.

How would be the best option to disable that option or use the alt option but disable the default the legend option?

**Comment by dsantxez** [comment]
I have still found one issue with this approach. The default legend is still available for the user unless I force programatically to show the AltLegend at the same place as the regular legend. Is there a programatically way to disable showing the regular legend and to be able to control the altLegend from the context menu of the plot?

**Comment by epezent** [comment]
See ImPlotLegendFlags_NoButtons and/or ImPlotLegendFlags_NoMenu

**Comment by dsantxez** [comment]
I see now that I was using the 0,9 version, we are using from vcpkg the ImPlot library. Sorry my bad, I will use directly the files from the latest version.

Thank you for your quick reply
