### ISSUE TITLE
ImGuiKeyModFlags not declared

### ISSUE THREAD

**Issue by jvannugteren** [epezent/implot#318]
In recent version of imgui (docking branch) and implot (master branch) I get compile errors for implot_demo.cpp about `ImGuiKeyModFlags` not being declared. These enums are in imgui_internal.h which is indeed not included. Can be fixed by adding `#include "implot_internal.h"` to implot_demo.cpp.

**Comment by epezent** [comment]
Requiring an internal header to use functionality exposed in the public header is less than ideal. We should find another path forward or kindly ask @ocornut to restore ImGuiKeyModFlags (note I have not looked at this in detail, so there may be a new alternative I'm not aware of).

**Comment by ocornut** [comment]
Interesting, I didn't realize you were using this! it marked somehow implied to be private. Let me investigate your use and I may move it back.

**Comment by ocornut** [comment]
Weirdly, ShowInputMapping() is not actually called anywhere in implot_demo.cpp so technically you should not need it. 
But for user configuration purpose it makes sense to expose KeyModsFlags for simple storage. Will apply a change.

**Comment by epezent** [comment]
Thank you, Omar!

**Comment by ocornut** [comment]
https://github.com/ocornut/imgui/commit/49e38a5b320629d1f982e1838dca2c89069a9aba
Done and also merged in Docking

**Comment by jvannugteren** [comment]
Thanks. I checked and the issue is resolved.

**Comment by ocornut** [comment]
FYI the type was renamed in 1.88 WIP
https://github.com/ocornut/imgui/commit/2c03aac6d30720d8f717dcd9cbb8b9a6799396b8
And I have submitted fixing PR here:
https://github.com/epezent/implot/pull/347
