### ISSUE TITLE
Resampling very large data sets

### ISSUE THREAD

**Issue by sonoro1234** [epezent/implot#323]
I would like to plot a very large data set (for example an audio file loaded in memory).
I cant just give the data to PlotLine or PlotLineG as performance is terrible.
I would need to know from which bin to which bin must be ploted and the width in pixels to be ploted. With this data I would be able to resample the data and give it to PlotLine.
Initial and last bin depend on the zoom used and the horizontal displacement of the data as set by the user with mouse.

How could this be done with implot?

**Comment by epezent** [comment]
You can use `GetPlotSize()` and `GetPlotLimits()` to get the pixel size and min/max coordinates:

```cpp
if (ImPlot::BeginPlot("My Audio")) {
    ImPlot::SetupAxes("Time [s]","Amplitude");
    auto widthPix = ImPlot::GetPlotSize().x;
    auto t1 = ImPlot::GetPlotLimits().X.Min;
    auto t2 = ImPlot::GetPlotLimits().X.Max;
    // use values to resample data, then plot
    // ...
    ImPlot::PlotLine(...);
    ImPlot::EndPlot();
}
```

**Comment by sonoro1234** [comment]
Thanks for the hints!!
Now experimenting with different resamplig strategies.

As I fill the time buffer with only the nedded times I have lost the hability of double-clicking in the plot to fit all data (all length of sound)

Is there a way to get this double-click so then I will do t1=0, t2=fulltimeofsound?

**Comment by epezent** [comment]
Ah, yea that is an issue with manually pruning data. A simple workaround is to plot 4 dummy points at the extreme corners of the waveform. If you supply a label prepended with "##` and set the points' color to transparent, it will be as if they aren't even there. 

We may want to eventually add a proper API for these, e.g. `ImPlot::ExtendFitRange` or something along those lines.

**Comment by sonoro1234** [comment]
> plot 4 dummy points

sorry, with which function should they be plotted

**Comment by sonoro1234** [comment]
I have got it working with LuaJIT-ImGui except for the 4 dummy points

```Lua
--- load soundfile
local ffi = require"ffi"
local sndf = require"sndfile_ffi"
local filename = "african_room.wav";
local info = sndf.get_info(filename)
print(info.frames,info.channels)
local buffer = ffi.new("float[?]",info.frames*info.channels)
local sf = sndf.Sndfile(filename)
sf:readf(buffer)
sf:close()

----normalize buffer
local maxi = -math.huge
local abs = math.abs
for i=0,tonumber(info.frames*2)-1 do
    local val = abs(buffer[i])
    maxi = maxi > val and maxi or val
end
local invmaxi = 1/maxi
for i=0,tonumber(info.frames*2)-1 do
    buffer[i] = buffer[i]*invmaxi
end


----take left buffer to plot
local bufferL = ffi.new("float[?]",info.frames)
for i=0,tonumber(info.frames)-1 do
    bufferL[i] = buffer[i*2]
end
buffer = nil

--- resample functions
local max,min = math.max, math.min
local function clip(v,l,h)
    return max(l,min(h,v))
end
local function Resample(W,t1,t2,info,Buf)
    local Byl = ffi.new("float[?]",W) --amplitude low
    local Byh = ffi.new("float[?]",W) --amplitude hight
    local Bt = ffi.new("float[?]",W) -- time
    local nbins = math.floor((t2-t1)*info.samplerate)
    local facx = tonumber(nbins/W)
    local binle = math.floor(facx+0.5)
    local frames = tonumber(info.frames)
    for i=0,W-1 do
        local binini = math.floor(t1*info.samplerate+i*facx)
        local inibin = clip(binini,0,frames-1)
        local endbin = clip(binini+binle-1,0,frames-1)
        Bt[i] = t1+ i*(t2-t1)/(W-1)
        Byl[i] = math.huge
        Byh[i] = -math.huge
        for j=inibin,endbin do
            local value = Buf[j]
            Byl[i] = Byl[i] < value and Byl[i] or value
            Byh[i] = Byh[i] > value and Byh[i] or value
        end
    end
    return Bt,Byl,Byh
end

-- imgui
local igwin = require"imgui.window"

local win = igwin:GLFW(800,400, "wav",{vsync=true})
win.ig.ImPlot_CreateContext()

function win:draw(ig)
    ig.ImPlot_ShowDemoWindow()
    ig.Begin("Waveform")
        if ig.ImPlot_BeginPlot("wav",ig.ImVec2(-1,-1)) then
            ig.ImPlot_SetupAxes("Time [s]","Amplitude");
            ig.ImPlot_SetupAxisLimits(ig.lib.ImAxis_Y1, -1, 1, ig.lib.ImPlotCond_Always);
            local widthPix = ig.ImPlot_GetPlotSize().x;
            local t1 = ig.ImPlot_GetPlotLimits().X.Min;
            local t2 = ig.ImPlot_GetPlotLimits().X.Max;
            local Bt,Byl,Byh = Resample(widthPix,t1,t2,info,bufferL)
            ig.ImPlot_PlotShaded("L",Bt, Byl,Byh,widthPix);
            ig.ImPlot_EndPlot();
        end
    ig.End()
end

local function clean()
    win.ig.ImPlot_DestroyContext()
end

win:start(clean)
```
![GIF](https://user-images.githubusercontent.com/1795930/153259556-84a61ed8-1c2f-4afc-a883-54a05fe414c8.gif)

**Comment by epezent** [comment]
Nice! Here's what I mean by four dummy points:

```cpp
float dummyX[] = [0, 0, audioLengthInSeconds, audioLengthInSeconds];
float dummyY[] = [1, -1, -1, 1];
...
ImPlot::SetNextLineStyle(ImVec4(0,0,0,0)); 
ImPlot::PlotLine("##DummyPointsForFitting",dummyX,dummyY,4); // transparent rect 
```

The line won't be visible or produce a legend entry, but it will be considered for fitting when double-click occurs.

**Comment by epezent** [comment]
It just occurred to me you don't need four dummy points, just two that form a diagonal.

**Comment by sonoro1234** [comment]
When we have time smaller than 0 (or time larger than audioLengthInSeconds) double-click fitting gets stuck on that times:

![GIF2](https://user-images.githubusercontent.com/1795930/153579427-3237c548-8e22-41e8-b25a-4822ed48f072.gif)

**Comment by sonoro1234** [comment]
```Lua 
function Resample(W,t1,t2,info,Buf,ch)
```
Takes pixelWidth, t1, t2, sound info, Buffer with sound data and desired channel.
Returns 3 Buffers: 2 with maximum and minimum values for each pixel and a third with times from t1 to t2. If user scrolls left the waveform plot times can be less than 0. If user scrolls right times can get bigger than length.

**Comment by epezent** [comment]
Ok. I think `Resample` needs to simply clamp t1 and t2 to the audio bounds.

```cpp
t1 = max(t1,0);
t2 = min(t2,audioLengthInSeconds);
```

In any case, this no longer sounds like an ImPlot issue and it seems like you just need to refine your resampling scheme. Is there anything else I'm missing?

**Comment by epezent** [comment]
PS -- loving the use of `PlotLine` and `PlotShaded` in your most recent GIF!

**Comment by sonoro1234** [comment]
> PS -- loving the use of `PlotLine` and `PlotShaded` in your most recent GIF!

Just copied from implot_demo `PlotShaded`

Thanks for all help
