### ISSUE TITLE
BeginPlot deprecated

### ISSUE THREAD

**Issue by Squareys** [epezent/implot#334]
Hi everyone!

Thanks for building such an awesome library.

I just upgraded to the latest ImPlot HEAD and found `ImPlot::BeginPlot()` to be deprecated. While I know that it's removal is planned for 1.0, [the code](https://github.com/epezent/implot/blob/master/implot.h#L1128) otherwise doesn't give a hint at what it was deprecated for. What should I be using instead?

Probably will figure out through git blame, but might be worth extending the comment for other people who stumble over this :)

Best,
Jonathan

**Comment by Squareys** [comment]
@marcizhu Thank you very very much!

For some reason I totally missed those release notes, sorry about that! Thank you very much for the kind reply despite the seemingly brain-dead issue opening 🙏

**Comment by marcizhu** [comment]
No problem! Glad to help :smile:
