### ISSUE TITLE
Durations for y axis

### ISSUE THREAD

**Issue by Flamaros** [epezent/implot#335]
I want to know if there is a way to display durations on y axis, like seconds, minutes, hours,...
I display timing results over time, and ideally I need that durations be merged when unzooming.

If there is nothing to do that actually I am interested to contribute.

**Comment by epezent** [comment]
It's not currently possible to use `ImPlotAxisFlags_Time` on vertical axes, but technically there is no reason we can't support it. I would be happy to review a PR if you'd like to contribute one!

**Comment by Flamaros** [comment]
Durations are a little different than time, so do I need to create a new flag?

And for the merging of values when unzooming, does it should be in Implot or Implot should only provide an API to allow to know what is the current zooming level and let him do the merge values? What I need here is to be able to show durations as seconds when zoomed in, and as minutes or hours when unzooming (sum of durations per days, weeks, years,...)

**Comment by epezent** [comment]
Ah, I misunderstood your proposal. I was under the impression you simply wanted ImPlotAxisFlags_Time to work for y-axes. 

I believe what you want could be implemented using the current public API. Take a look at `ShowDemo_TickLabels` and `MetricFormatter` in `implot_demo.cpp`.

**Comment by Flamaros** [comment]
Hello,

Thx pour tips, I think I have to use `SetupAxisTicks` function that takes values as parameter to be able to have fixed values while converting durations originally in seconds in other time scales.

**Comment by Flamaros** [comment]
I made some tests and SetupAxisTicks is exactly the function I need, but I a have an issue with operations orders.
I need to call GetPlotLimits to know which is the visible time frame (limits of x axis), and depending on that I want to compute data to display.  As I draw bars I have to determined bar width and I accumulate durations (y axis) depending on this width (the date range of the bar).
Sadly SetAxisTicks can't be called after GetPlotLimits (I have an assert in debug).

It seems that there is no way to get the plot limits of a particular axis to avoid the setup lock on others. I may try to use limits of the previous rendered frame, but it doesn't seems optimal as the accumulation behavior may introduce important changes on the scale of the y axis when panning or zooming the x axis (and I use auto-fit of y axis).

Here is a screenshot with durations (y axis) converted from seconds to minutes:
![image](https://user-images.githubusercontent.com/1679168/159092361-02f3e20b-99ca-4c78-8b4b-5abe91a13807.png)
Labels are hard-coded here.

With the zoom level of the x axis in the screenshot, I think bars should represent accumulation of compile times over an hour (6-7: 7-8; 8-9,...).

**Comment by Flamaros** [comment]
thanks a lot for advices, I finally have something much cleaner:
![image](https://user-images.githubusercontent.com/1679168/160604048-1b3dc9f0-a377-41d8-ba41-95a6dc211751.png)
![image](https://user-images.githubusercontent.com/1679168/160604120-9b2eed25-dd29-4262-bf16-240f90891364.png)

I may try to add getters for ticks configuration to improve my computation of ideal bar width. IMO it might be much better if I have same number of bars than ticks.
