### ISSUE TITLE
reuse data across frames

### ISSUE THREAD

**Issue by matthijsvk** [epezent/implot#336]
Hi,

I want to make a plot where I draw an additional line every frame, so after a few seconds there are 100s of lines.
Is there a way to preserve the plot and only add the single line instead of redrawing everything every frame?
I found `ImPlot::GetPlotDrawList()`, but not sure if this could be used for that.
Thanks,

Matthijs

**Comment by epezent** [comment]
ImPlot is not designed to cache render data across frames, and likely never will. Neither is ImGui for that matter. You can do what you want by simply replotting all past lines on each new frame before plotting the new line.

**Comment by Nahor** [comment]
@matthijsvk, I'm not sure how easy it would be to do, but you might be able render the plot into a separate framebuffer/texture, and not clear that buffer between frames (as well as configuring ImGui/ImPlot to render without a background, or a transparent one)
