### ISSUE TITLE
Axes decorations are still rendered after passing ImPlotAxisFlags_NoDecorations 

### ISSUE THREAD

**Issue by swinefeaster** [epezent/implot#356]
is this a recent regression in v.0.13 or am i doing something wrong?

![image](https://user-images.githubusercontent.com/26147149/166523324-d85d6fef-0b55-4434-bab4-9b128a80042b.png)

`

    ImPlot::PushStyleVar(ImPlotStyleVar_PlotPadding, ImVec2{});
    ImPlot::PushStyleVar(ImPlotStyleVar_PlotBorderSize, 0.2f);
    {
        ImPlotFlags plotFlags = ImPlotFlags_Equal | ImPlotFlags_NoLegend | ImPlotFlags_AntiAliased | ImPlotFlags_NoMenus | ImPlotFlags_NoBoxSelect;
        {
            if (!showCaption)
            {
                plotFlags |= ImPlotFlags_NoTitle;
            }
        }

        if (ImPlot::BeginPlot(caption, plotData.size, plotFlags))
        {
            ImPlot::SetupAxis(0, nullptr, ImPlotAxisFlags_NoDecorations);
            ImPlot::SetupAxis(1, nullptr, ImPlotAxisFlags_NoDecorations);
            ImPlot::SetNextMarkerStyle(ImPlotMarker_Circle, 6, k_white, IMPLOT_AUTO, k_white);
            ImPlot::PlotScatterG("Data", [](void * data, int sampleIndex)
`

**Comment by epezent** [comment]
Your problem is that you are hardcoding a 1 for the y-axis index. Use `ImAxis_Y1`, which evaluates as 3 on my machine:

```cpp
        ImPlot::SetupAxis(ImAxis_X1, nullptr, ImPlotAxisFlags_NoDecorations);
        ImPlot::SetupAxis(ImAxis_Y1, nullptr, ImPlotAxisFlags_NoDecorations);
```
