### ISSUE TITLE
shaded stairs plot?

### ISSUE THREAD

**Issue by phraktle** [epezent/implot#357]
Is there a way to show a shaded stairs plot? The closest I was able to get visually was to show a stairs plot with a semi-transparent shaded plot underneath, but that has some obvious visual artifacts, as in this screenshot:

<img width="435" alt="screenshot" src="https://user-images.githubusercontent.com/333139/166641438-f1dd37f7-ccb9-40b1-9553-cc6b39301843.png">

**Comment by epezent** [comment]
The best solution I can currently offer is to add additional points to your call to `PlotShaded`. I think it's actually a good idea to add e.g. a `PlotSairsShaded` API function to do what you want, though. I can flag this for future work.

**Comment by phraktle** [comment]
Thanks, indeed as a workaround one could calculate the connecting points. It would be more convenient and performant to have the `PlotSairsShaded` call available (or perhaps a more general API to specify the fill and the line styles).

**Comment by epezent** [comment]
Hi, https://github.com/epezent/implot/commit/fc0fd112467c2be84bc56daa57612b0c579ff1af adds  `ImPlotStairsFlags_Shaded`:

![image](https://user-images.githubusercontent.com/29577475/175078998-5f088dc4-9ec9-4408-ab01-f617a5da9ba1.png)
