### ISSUE TITLE
Floating Point Precision

### ISSUE THREAD

**Issue by epezent** [epezent/implot#36]
There have been a few issues recently that would suggest we need to move from using `float` to `double` for plot coordinate values (at least internally for axis ranges and pixel conversions).  Namely this relates to precision needed when zooming (https://github.com/epezent/implot/issues/34 , https://github.com/epezent/implot/pull/33#issuecomment-628288094). Additionally, I know there's many of us in the science/robotics fields that may have double precision data as opposed to gaming devs using single precision. 

I've made some progress on the [double branch](https://github.com/epezent/implot/tree/double) and would appreciate another set of eyes on it. There's a chance I overlooked a few important casts or something to that effect. Note that the precision can be reverted by changing `typedef double ImPlotFloat;` at the top of `implot.h` to `float`.

I have not made `double` versions of each `PlotXXX` function yet. I see two paths forward here:

1) Remove `ImPlotFloat` typedef and explicitly use `double` internally. Expose both `double` and `float` versions of all our API functions. Data passed as `float` will be converted to `double` before being transformed to pixel space. My initial testing suggests this incurs around a 5% slowdown, which seems acceptable.
2) Keep `ImPlotFloat` typedef and allow the user to choose their floating point precision.  The signatures of all API functions will take `ImPlotFloat*` etc. This would mean less code to maintain, with the downside being users can't mix/match double and float data in the same application (easily). 

Thoughts?

**Comment by epezent** [comment]
I suppose a third option is to expose a templated API, but this would restrict usage from other languages and make the header a mess.

**Comment by ozlb** [comment]
I'm for option 2.

**Comment by Prinkesh** [comment]
Option 2 seems a better choice for most of the cases . 

Templated API could probably add more flexibility for adding different data structures as user input . Like in case of nanosecond timestamp where double won't suffice directly . 

Another example could be for sub aggregation of large dataset .

Suppose one has million of points . So directly plotting them would not be a good choice 
So we can extend functionalities for bucketing the data with averages or any other aggregation method of user choice . In this case users themselves can implement stride selection methodology and aggregation methods .

**Comment by epezent** [comment]
Thanks for the feedback. I agree that 2 is probably the way to go. We might actually prefer a macro:

```cpp
#ifndef ImPlotFloat
#define ImPlotFloat double
#endif
```
Which clients can optionally define beforehand in `imconfig.h` or at a project level. This would be the most ImGui thing to do, as far as I can tell.

@ocornut, any guidance on this matter?

**Comment by ocornut** [comment]
I haven't looked in details, but as for:

> I suppose a third option is to expose a templated API, but this would restrict usage from other languages and make the header a mess.

You could expose 2 functions on the outside, and have them call a templated function that completely internals, so none of the templating is exposed..
See how dear imgui does for SliderScalar etc.

**Comment by epezent** [comment]
> I suppose a third option is to expose a templated API, but this would restrict usage from other languages and make the header a mess.
> 
> You could expose 2 functions on the outside, and have them call a templated function that completely internals, so none of the templating is exposed..
> See how dear imgui does for SliderScalar etc.

Yes, that's what I would have probably done for (1) above. The main question we are trying to answer is do we (a) expose both `float` and `double` versions of all our functions or (b) let the user define the floating point type with a typedef or macro and only expose functions accepting that type. I was leaning toward (b), but in hindsight (a) might be the more ImGui way.

**Comment by sergeyn** [comment]
Hi,
If I may add my input on the "double branch". I really don't like how you approached that problem with global type if everything is double or float. That is not the way to go! Double or float - these are simply different input types. You should be able to plot float and double plots at the same time. 
Internally, you may (or may not) do the scaling math in double precision for float plots, but that's it. nothing else should change, you have a good enough api atm. so please just extend it to accept double precision plots and that's it!

Thanks.

**Comment by epezent** [comment]
I decided to support both `float` and `double` versions of all plotting functions. Internally, ImPlot is using double precision, and generic API functions such as `SetNextPlotLimits` take `double` since that supports both types without explicit casts. The demo can be compiled using either `float` or `double` precision for testing purposes.

https://github.com/epezent/implot/commit/aa23d95e21cb261e933995891049ea8c8f213cd1
