### ISSUE TITLE
scrolling/zooming

### ISSUE THREAD

**Issue by aDioS786** [epezent/implot#363]
Hi,
I been looking into and trying to figure out but cant find. When zooming in/out using mouse wheel, the GetContext/GetIO and few other functions i've tried, doesn't provide any way to figure out that how much have we zoomed in / out on current plot. Kindly let me know if there's a way to achieve this.

**Comment by epezent** [comment]
You can use `GetPlotLimits` and compare this to the initial or previous value to get an estimate of relative zoom. You'll likely want to compare the size (i.e. max - min limit) for zooming.
