### ISSUE TITLE
ColormapScale function cannot handle inverted min / max ranges

### ISSUE THREAD

**Issue by WeirdRubberDuck** [epezent/implot#368]
See example in demo, where I set min > max: 
![image](https://user-images.githubusercontent.com/8808894/174036551-7558472b-efb0-4ece-8153-171ec23c48a4.png)

The ticks and labels do not show up in the ColromapScale. Would be great if they did, or if there was another way to invert the color map

**Comment by epezent** [comment]
Thanks for flagging this -- we can work in support for inverted scales. I think it would make more sense to enable inversion with e.g. `ImPlotColormapScaleFlags_Invert` than misconstruing the min/max values (this flag could also allow for more options/customization in the future). Thoughts?

**Comment by epezent** [comment]
Hi, let me know if https://github.com/epezent/implot/commit/0f4d4dccc333c4e5aeebeb27866857cc45627dfe helps you achieve the functionality you need. See below:


![cmapscale](https://user-images.githubusercontent.com/29577475/174522382-82bf0ee6-ec71-448a-b24d-de81d748008a.gif)

**Comment by WeirdRubberDuck** [comment]
I agree, an invert flag is perfect. 

However, in that flip, I would expect 0 db to be mapped to yellow and 100 dB to be mapped to purple when the `ImPlotColormapScaleFlags_Invert` is set to true

**Comment by epezent** [comment]
Oh! I completely missed your point. I see now you want to invert the mapping from from the data range to color range. I thought you just wanted to turn the widget upside down 😂

In that case, I think your original proposal of flipping min/max scale is the right one. I'll take a look and figure out why that's not working. Sorry for the mixup!

**Comment by epezent** [comment]
Ok, give https://github.com/epezent/implot/commit/6c00109636a78cd317de2b2a02744deec523b181 a go! To summarize the new behavior, `scale_min > scale_max` will reverse the mapping from the scale range to the color range (i.e. only affects axis direction) and `ImPlotColormapScale_Invert` will invert both the colormap bar and axis. See below:

||scale_min < scale_max|scale_min > scale_max|
|---|---|---|
|**ImPotColormapScaleFlags_None**|![image](https://user-images.githubusercontent.com/29577475/174605988-d42565fd-536c-4e34-b94f-586e8046cee5.png)|![image](https://user-images.githubusercontent.com/29577475/174606144-8e50ed00-667a-4166-a67e-df0f9d07c2ce.png)|
|**ImPotColormapScaleFlags_Invert**|![image](https://user-images.githubusercontent.com/29577475/174606569-a8328092-3946-4237-9345-425c8034b3f7.png)|![image](https://user-images.githubusercontent.com/29577475/174606276-16146dba-16bc-4a11-b5a1-3944b9a5547c.png)|

**Comment by WeirdRubberDuck** [comment]
Cool! Have some other things to prioritize but will try that out asap 😄
