### ISSUE TITLE
Mouse Text for dates shows double.

### ISSUE THREAD

**Issue by MarkusWende** [epezent/implot#378]
Since ImPlotAxisFlags_Time is removed I noticed, that the mouse position text for dates is not showing the date but the double. 

![Screenshot 2022-07-07 111217](https://user-images.githubusercontent.com/38251717/177738147-853ff276-6dc6-4735-9cc2-d242883d21f4.png)

**Comment by epezent** [comment]
Hey! Sorry about that; noticed this a few days ago as well. Our formatting internals changed quite a bit recently, and this issue got overlooked . I've pushed a temporary fix in https://github.com/epezent/implot/commit/1fed5c2c193729e224f05c12d954c0507e4cf7b0, but I'm going to leave this issue open as a reminder that we need a better design to handle time formatted mouse text.
