### ISSUE TITLE
The "drag Points and drag lines" are not draggable in the demo window.

### ISSUE THREAD

**Issue by zhengzh** [epezent/implot#387]
![drag_points](https://user-images.githubusercontent.com/3636536/184330064-0032bc24-7876-49f3-836c-feced1bc3c9d.gif)

I run the demo with the newest `imgui` libray and `implot` libray, everything is working fine except the draggable points and draggable lines and draggable rectangles. They are not draggable, Please help!

**Comment by epezent** [comment]
Hi! I'm not seeing this issue using the latest master branches: ImGui 1.89 (18808) and ImPlot 0.14. Can you confirm you are on the latest? Note we did see this issue a few months ago, but it was fixed in #355. Probably you are using an ImPlot release where the fix hasn't been applied.

**Comment by zhengzh** [comment]
@epezent  Thanks for your responds! Sorry, my mistake, I use vcpkg to intall the libraries (`imgui |Version: 1.87, implot |Version: 0.13`)， which are not the latest.
