### ISSUE TITLE
Crash on drag&drop demo

### ISSUE THREAD

**Issue by rasky** [epezent/implot#39]
I can reproduce a crash in the implot drag & drop demo:

 * Pause the graph
 * Clear the graph
 * Drag & drop any label to the graph

This is the crash:
```
↪ ./example_sdl_opengl3
Assertion failed: (i < Size), function operator[], file ../../imgui.h, line 1326.
fish: './example_sdl_opengl3' terminated by signal SIGABRT (Abort)
```

OSX 10.14.16, running example_sdl_opengl3. I'm using today's imgui master branch.

**Comment by epezent** [comment]
Thanks, it has been fixed.
