### ISSUE TITLE
Centre Screen

### ISSUE THREAD

**Issue by aDioS786** [epezent/implot#398]
Hi,
I've been trying to do a centre screen on another key press, so far if double click is it, it automatically move plot focus to centre. Do we have a api call which we can call to focus/move to centre of screen? Thanks

**Comment by epezent** [comment]
```cpp
// Set an upcoming axis to auto fit to its data.
IMPLOT_API void SetNextAxisToFit(ImAxis axis);

// Sets all upcoming axes to auto fit to their data.
IMPLOT_API void SetNextAxesToFit();
```

You can use these functions to trigger a fit for the upcomming plot. Call before BeginPlot if the user presses the desired key.

**Comment by aDioS786** [comment]
> ```c++
> SetNextAxisToFit
> ```

Many Thanks, epezent, is there a way to reset the axis/axes to fit to given plotted coordinates? Say we have plotted several data on graph and i scroll right of graph, from that point if I like to move the graph or focus on to Data 1  (which is plotted somewhere 250,250 coordinates, do we have any api to do this? Thanks
