### ISSUE TITLE
Line rasteriation issues for dense plots

### ISSUE THREAD

**Issue by sergeyn** [epezent/implot#42]
When you have super dense plots (many points hit a pixel), you can see holes in the rasterization pattern. Consider following plot, which plots a line:
`ImPlot::PlotLine("line, [](void*, int idx) { float v = float( 3.0 * idx / (1000000 - 1)); return ImVec2(v, v);        }, nullptr, 1000000);`
You can observe single pixels missing on a plot. 
I believe it's because triangles generated for line segments do not have exactly same coordinates. 
(PS. you need my million line PR for this to work)

**Comment by sergeyn** [comment]
Any comments about this issue ? It'd be nice to know your ideas on further developments in this area (if any)

**Comment by epezent** [comment]
Hi @sergeyn , sorry for the slow reply and not addressing open PRs. I've been busy with other work and hope I can get to them soon.

Regarding this issue, I think this falls under the need to (optionally) downsample user data. For example, see the documentation for [pyqtgraph](https://pyqtgraph.readthedocs.io/en/latest/graphicsItems/plotdataitem.html):

|||
|---|---|
|**downsampleMethod**|‘subsample’: Downsample by taking the first of N samples. This method is fastest and least accurate. ‘mean’: Downsample by taking the mean of N samples. ‘peak’: Downsample by drawing a saw wave that follows the min and max of the original data. This method produces the best visual representation of the data but is slower.

**Comment by sergeyn** [comment]
But I'm not sure how exactly does this addresses the issue. The problem is that points at the same place from neighbor line segments don't end up at the same spot. With dense rendering like I do problem just becomes obvious, it will not go away if you perform a reduction, unless you reduce everything to one line of course.
I mean that something like this: https://github.com/mattdesl/extrude-polyline  needs to get implemented to properly draw connected segments.

**Comment by epezent** [comment]
Well, downsampling reduces the chance that you have many points hitting a single pixel, I suppose.

Regarding connected segments: If I'm not mistaken, this is what ImGui's `AddPolyline` does by default (I can't remember for sure, perhaps I'm wrong). Can you swap out ImPlot's implementation with a call to this function and see if it improves?

**Comment by sergeyn** [comment]
Will try , thanks. I'm honestly not that familiar imgui internals yet. Another way I am thinking about is to push actual line strips to gpu. This would reduce amount of data generated and you get thin connected lines without much effort.
The default line rendering you have is for performance reasons, correct ? I could further significantly optimize line rendering but I don't feel like investing time into a method which doesn't produce accurate result.

**Comment by epezent** [comment]
I agree that we could get optimizations by bypassing ImGui and going straight to the GPU, but I'm hesitant to support that right now since it would be a massive undertaking to handle all the potential backends (we'd essentially have to provide an implementation for every example backend ImGui does).

**Comment by epezent** [comment]
@sergeyn , could you post some screenshots of what exactly is happening here. I'm curious.

**Comment by sergeyn** [comment]
![image](https://user-images.githubusercontent.com/668090/83454860-25b8c000-a45d-11ea-856d-7783666c8d23.png)

**Comment by epezent** [comment]
@sergeyn , I'm testing your PR. Can you provide the code for the plot above?

**Comment by sergeyn** [comment]
```ImPlot::PlotLine("spiral",
         [](void*, int idx) {
            float r = 0.9f; // outer radius
            float a = 0; // inner radius
            float b = 0.05f; // incerement per rev
            float n = (r - a) / b; // number  of revolutions
            double th = 2 * n * M_PI; // angle
            float Th = float(th * idx / (1000000 - 1));
            return ImVec2(0.5f+(a + b*Th / (2.0f * (float) M_PI))*cosf(Th), 0.5f + (a + b*Th / (2.0f * (float)M_PI))*sinf(Th));            
         }, nullptr, 1000000);```

Note that when plot completely gets culled away, you may see garbage on screen (same as you have in your master currently), which is fixed by [this](https://github.com/ocornut/imgui/pull/3232)  PR. It's not a problem of plot rendering.

**Comment by epezent** [comment]
Fixed in https://github.com/epezent/implot/pull/41

**Comment by sergeyn** [comment]
May I ask how exactly is this fixed ? 
As you can see on the image - here almost every other pixel is missing.
![image](https://user-images.githubusercontent.com/668090/83977528-64d58e00-a901-11ea-8d42-218389d12c4e.png)

**Comment by epezent** [comment]
Apologies, I misremembered the issue. I thought this one was related to the spiral truncating. 

Yes, this does seem to still be an issue. As I said before, I think the best solution for this is to down sample the data with the user's permission.

**Comment by sergeyn** [comment]
>Yes, this does seem to still be an issue. As I said before, I think the
best solution for this is to down sample the data with the user's
permission.
Realistically no one will do that, and it won't work for scientific
purposes. Proper solution would be to generate proper linestrip with caps
at sharp angles. I understand that you care about perf first. I'll maybe
try give it a shot at some point.

**Comment by epezent** [comment]
Out of curiosity, what sort of data are you trying to plot where this is a real issue?

**Comment by sergeyn** [comment]
time series with possibility for extreme zoom-outs. I simple want them to look nice.

**Comment by epezent** [comment]
I'm closing this issue because:

1) We are never going to support mitered edges...the cost is just too high
2) Downsampling, as you said, should NOT be default, and it's actually quite simple to implement using the existing offsetting and striding features. An example of this can be seen in the new `Time Formatting` demo, where 31,622,400 points are dynamically downsampled and plotted:

![time-zoom](https://user-images.githubusercontent.com/29577475/92335619-0635c280-f05e-11ea-8605-a9628b21fd7f.gif)
