### ISSUE TITLE
Make flags easier to use via FFI

### ISSUE THREAD

**Issue by charlesdaniels** [epezent/implot#43]
This is relating to the effort to bind implot and use it in GIU. [Relevant GIU issue](https://github.com/AllenDang/giu/issues/53).

I've gotten some of the basics of implot bound into imgui-go already working. However one issue I ran into was that some of the enum types don't have defined values (they are enumerated automatically). This makes them hard to use via FFI. To work around this, I modified our in-tree fork to split the relevant enums out into their own header, which let me interface with it from Cgo. (`implot.h` cannot be directly imported into Cgo, since it doesn't understand many of the C++-isms)

There are two ways to work around this that I can think of:

1. Separate the flags into their own header as I did ([example](https://github.com/charlesdaniels/giu/blob/master/imgui/implotFlags.h))
2. Assign specific values to each flag, so the same values can be hard-coded on the other side of the FFI.

I would be happy to make the needed changes and submit a PR, but I wanted to see if @epezent had a preference between the two before I do the work, or if you can think of a better way to do this.

**Comment by epezent** [comment]
I'd prefer not to split the headers, so (2) would be my choice if necessary. How are you handling this issue for ImGui's flags?

**Comment by charlesdaniels** [comment]
It seems like they also do (2).

**Comment by epezent** [comment]
I'm looking at `imgui.h` in `imgui-go` and some of the enums are still valueless. Maybe I'm misunderstanding the problem or not looking in the right place. Regardless, go ahead and submit a PR and I'll take a look.

**Comment by charlesdaniels** [comment]
> I'm looking at `imgui.h` in imgui-go and some of the enums are still valueless. Maybe I'm misunderstanding the problem or not looking in the right place.

The valueless enums appear to be ones which don't need to be called via FFI. I didn't look exhaustively, but I didn't notice any that I checked where the Go side needed to use the enum for anything.

That said, [apparently](https://stackoverflow.com/a/30312219) the standard specifies that enums are enumerated 0, 1, ... n. So as long as the enum values are never re-ordered, they should always come up with the same number. TBH I never knew that, I assumed that the compiler could do whatever it wanted.

So I guess option 3 is leave it as it is, but don't re-order the enum values relative to one another. (or at lest not too often, since the Go bindings would have to be manually updated in such cases).

**Comment by epezent** [comment]
My inclination is to leave ImPlot as it is (which attempts to conform to ImGui as much as possible). That said, this is still an evolving API, so do expect the enums to change as ImPlot matures.

**Comment by charlesdaniels** [comment]
I think I agree that's the way to go.

If we really need this, I can always maintain the modifications in GIU's in-tree fork. Or I may simply maintain the split header files. Either way, all things considered, I think it would be most reasonable to keep the implot flag set up as it is.
