### ISSUE TITLE
Plot with ImPlotScale_Time and X axis in microseconds

### ISSUE THREAD

**Issue by hinxx** [epezent/implot#439]
My X axis data points are represented as number of microseconds from epoch. In the `Demo_TimeScale` demo I see that seconds are used.
Can I have the X axis constructed with microsecond ticks?

**Comment by epezent** [comment]
You can try using the `ImPlotTime` struct from `implot_internal.h` to convert a time point consisting of second and microseond parts to `double`.

```cpp
int s = 10;
int us = 123456;
ImPlotTime myTime(s,us); // 10.123456 s
double myDouble= t.ToDouble(); // plot this
```
