### ISSUE TITLE
Background area of plot can be transparent?

### ISSUE THREAD

**Issue by starwindz** [epezent/implot#45]
Thank you very much for the great work.
I have some question about real-time plot. I would like to make the background area of plot to be transparent. 
https://github.com/epezent/implot/blob/master/implot_demo.cpp#L271

Tried to find related options or parameters but could not find out. Are there any ideas about this feature?

**Comment by epezent** [comment]
Try:
```cpp
ImPlot::PushStyleColor(ImPlotCol_FrameBg, {0,0,0,0});
ImPlot::PushStyleColor(ImPlotCol_PlotBg, {0,0,0,0});
if (ImPlot::BeginPlot(...)) {
    ...
    ImPlot::EndPlot();
}
ImPlot::PopStyleColor(2);
```

Of course, you won't be able to make it any more transparent than the ImGui window that it is drawn over, so you'll have to push the appropriate styling variables there as well.

**Comment by starwindz** [comment]
Great, it works!
Thank you very much!

One more question, legend area such as "Data 1" and "Data 2" in the plot can be also transparent?
https://github.com/epezent/implot/blob/master/implot_demo.cpp#L289

**Comment by epezent** [comment]
The legend color is controlled by `ImGuiCol_PopupBg`, so use:

**ImGui**::PushStyleColor(ImGuiCol_PopupBg,{0,0,0,0});

**Comment by starwindz** [comment]
Very nice, it also works fine!
Thank you very much again.
