### ISSUE TITLE
Legend Font

### ISSUE THREAD

**Issue by aDioS786** [epezent/implot#462]
Hi,
Is there a way to apply a different font to legend names, I can't seem to get it to work, tried pushing fonts before/after plotting but doesn't work. Also like we have SetNextAxisToFit, is there a way to centralized given plot coordinates to middle of screen? thanks

**Comment by epezent** [comment]
There is currently no way to have different fonts per legend item. This would take quite a bit of effort and special APIs. I do not plan to support such a feature. Sorry for the inconvenience.
