### ISSUE TITLE
vertical asymptotes

### ISSUE THREAD

**Issue by sonoro1234** [epezent/implot#47]
When plotting `1/x` or similar it would be useful to have a vertical line appearing for infinite values.
Does it make sense?

**Comment by epezent** [comment]
Makes sense, but I'm not sure how we'd approach it generically. Initial thought is to check if a point is infinite, and if so draw a line back to 0. But then this would look like crap if multiple or consecutive values were infinity, so there'd have to be some extra logic in there to deal with that. I'm somewhat resistant to adding more checks and logic to the line rendering functions for performance reasons. Do you have any thoughts on how it could be done efficiently? 

Looks like MATLAB can draw asymptotes, but only when plotting a symbolic expression. 
https://www.mathworks.com/help/symbolic/find-asymptotes-critical-and-inflection-points.html

**Comment by sonoro1234** [comment]
>  But then this would look like crap if multiple or consecutive values were infinity

It is not the typical case where asymptotes happen only for specific values

**Comment by epezent** [comment]
Valid point. It might be easier than I initially thought. I can possibly look at it in the near future. Feel free to submit a PR in the meantime.

**Comment by epezent** [comment]
After some thought, I don't think this is something we need to address right now. I'm closing the issue.
