### ISSUE TITLE
ImPlot freezing after a while - Raspberry Pi

### ISSUE THREAD

**Issue by DanielMartensson** [epezent/implot#488]
I'm using ImPlot on Raspberry Pi. If I just show a constant plot for an hour or two, then my Raspberry Pi is freezing. It's the application of ImPlot that causing this problem.

But I don't know why.

My codes for plotting an ImPlot are here
https://github.com/DanielMartensson/GoobySoft/blob/d72ba1af79e76c5804d92a52c92e4ab9d3fbe391/GoobySoft/Windows/Dialogs/MeasurementDialogs/ViewMeasurementDialog/ViewMeasurementDialog.cpp#L122C1-L126C5

https://github.com/DanielMartensson/GoobySoft/blob/d72ba1af79e76c5804d92a52c92e4ab9d3fbe391/GoobySoft/Windows/Dialogs/MeasurementDialogs/ViewMeasurementDialog/ViewMeasurementDialog.cpp#L9-L32

My question is:
Have I forgot something?

I'm calling with a create context, but I never call destroy context. Can this be the issue?

````
ImPlot::CreateContext();
````

**Comment by ozlb** [comment]
`ImPlot::CreateContext();` must be called only once after `ImGui::CreateContext();`, so in your project here in [GoobySoft/GoobySoft.cpp](https://github.com/DanielMartensson/GoobySoft/blob/4c2384bec5b8e117e8efa34fbfb551da7bbd0463/GoobySoft/GoobySoft.cpp#L76)
Do not forget about DestroyContext() functions

**Comment by DanielMartensson** [comment]
> DestroyContext()

@ozlb Thank you. It worked. Did not understand that `ImPlot::CreateContext();` should only be called once. But I don't even call `ImGui::CreateContext();`.
