### ISSUE TITLE
How to customize interaction of the plot drawn by the `ImPlot`?

### ISSUE THREAD

**Issue by autra-tech-zhanghao** [epezent/implot#495]
Hi, I want to rewrite some interaction logic of the plot. For example, a line chart which can not zoom on x direction but still can in y direction. I found that there is the Flag `ImPlotFlags_NoInputs` that can disable the default behavior of the plot, but as it says, it also can't receive any input event so my custom interaction logic can't be called either. Is there any other way? Thanks a lot~

**Comment by epezent** [comment]
Hi, you can use `ImPlotAxisFlags_Lock` on the x-axis to prevent scroll wheel zoom for this axis only.
