### ISSUE TITLE
Find data extents

### ISSUE THREAD

**Issue by ozlb** [epezent/implot#50]
In PlotEx()
```cpp
    // find data extents
    if (gp.FitThisFrame) {
        for (int i = 0; i < count; ++i) {
            ImPlotPoint p = getter(i);
            FitPoint(p);
        }
    }
```
is not handling the case of constant y values where result of FitPoint() will return gp.ExtentsX.Min and gp.ExtentsX.Max equal. This will stuck scrolling and Y resizing interaction.

**Comment by epezent** [comment]
We could check if xmin==xmax and ymin==ymax after a fit, and if so, add a small amount of buffer room to both min and max. Difficult to say what that value you should be. Perhaps we just shouldn't fit the data if that condition is met.

**Comment by epezent** [comment]
We also need to harden the zooming code, so that axes never get stuck in the first place.

**Comment by epezent** [comment]
This code currently exists in `BeginPlot`:

```cpp
    if (plot.XAxis.Range.Max <= plot.XAxis.Range.Min)
        plot.XAxis.Range.Max = plot.XAxis.Range.Min + DBL_EPSILON;
```

I guess we need a bigger epsilon here.

**Comment by ozlb** [comment]
> We could check if xmin==xmax and ymin==ymax after a fit, and if so, add a small amount of buffer room to both min and max. Difficult to say what that value you should be. Perhaps we just shouldn't fit the data if that condition is met.

this is what i did temporary, but probably the best is to limit to an "harden" value that could match with minimum axis tick gap; in other words a sort of `ImPlotRange.Epsilon`

**Comment by ozlb** [comment]
Temporarly I did this but probably we do need something else:
```cpp
#define IM_PLOT_EPSILON (FLT_EPSILON)
```
replaced all DBL_EPSILON with IM_PLOT_EPSILON and clamp is like this

```cpp
    if ((plot.XAxis.Range.Max - plot.XAxis.Range.Min) <= (2 * IM_PLOT_EPSILON)) {
        plot.XAxis.Range.Min -= IM_PLOT_EPSILON;
        plot.XAxis.Range.Max += IM_PLOT_EPSILON;
    }
    for (int i = 0; i < MAX_Y_AXES; i++) {
        if ((plot.YAxis[i].Range.Max - plot.YAxis[i].Range.Min) <= (2 * IM_PLOT_EPSILON)) {
            plot.YAxis[i].Range.Min -= IM_PLOT_EPSILON;
            plot.YAxis[i].Range.Max += IM_PLOT_EPSILON;
        }
    }
```

**Comment by epezent** [comment]
Any particular reason you used FLT_EPSILON and not DBL_EPSILON in the define?

**Comment by ozlb** [comment]
Because in double internal context FLT_EPSILON can be handled while DBL_EPSILON not; as you know the minimum increment that can be handled by floating point numbers depends by the values. For float IEEC754 when the number is greater that 2^24 the minimum increment becomes 1.0...
It's not the proper solution to use FLT_EPSILON but for the numbers absolute values I'm using it covers the issue; it's a temporary work around.

**Comment by ozlb** [comment]
what about `ImPlot::SetNextPlotEpsilonX` and `ImPlot::SetNextPlotEpsilonY`?

**Comment by epezent** [comment]
I'm not sure how useful that would be. We just need to fix the epsilon issues under the hood. 

FWIW, [pyqtgraph](https://github.com/pyqtgraph/pyqtgraph) suffers similar issues. Zooming in really closely locks the axis from dragging, and zooming beyond ~1e308 causes the application to crash.

**Comment by ozlb** [comment]
I update to latest version and (as reminder) there is still this little problem.
You can replicate the issue plotting a constant value.

![Peek 2020-08-26 07-15](https://user-images.githubusercontent.com/3250876/91258867-a8f06600-e76d-11ea-8326-5ed1134d028e.gif)

**Comment by ozlb** [comment]
If someone is suffering by this issue, temporary this is a workaround.
PS: clamp must be done also under `SCROLL INPUT` section.

```cpp
    // FIT DATA --------------------------------------------------------------

    if (gp.FitThisFrame && (gp.VisibleItemCount > 0 || plot.Queried)) {
        if (gp.FitX && !ImHasFlag(plot.XAxis.Flags, ImPlotAxisFlags_LockMin) && !NanOrInf(gp.ExtentsX.Min)) {
            plot.XAxis.Range.Min = gp.ExtentsX.Min;
        }
        if (gp.FitX && !ImHasFlag(plot.XAxis.Flags, ImPlotAxisFlags_LockMax) && !NanOrInf(gp.ExtentsX.Max)) {
            plot.XAxis.Range.Max = gp.ExtentsX.Max;
        }
        for (int i = 0; i < IMPLOT_Y_AXES; i++) {
            if (gp.FitY[i] && !ImHasFlag(plot.YAxis[i].Flags, ImPlotAxisFlags_LockMin) && !NanOrInf(gp.ExtentsY[i].Min)) {
                plot.YAxis[i].Range.Min = gp.ExtentsY[i].Min;
            }
            if (gp.FitY[i] && !ImHasFlag(plot.YAxis[i].Flags, ImPlotAxisFlags_LockMax) && !NanOrInf(gp.ExtentsY[i].Max)) {
                plot.YAxis[i].Range.Max = gp.ExtentsY[i].Max;
            }
            //Find data extents #50 issue - BEGIN
            if ((plot.YAxis[i].Range.Max - plot.YAxis[i].Range.Min) <= (2.0 * FLT_EPSILON))  {
                plot.YAxis[i].Range.Max += FLT_EPSILON;
                plot.YAxis[i].Range.Min -= FLT_EPSILON;
            }
            //Find data extents #50 issue - END
        }
    }
```

**Comment by epezent** [comment]
I added your fix to master and also extended this to the x-axis for vertical lines. Sorry this simple fix took me so long to get to.
