### ISSUE TITLE
Colorbar labels cropped

### ISSUE THREAD

**Issue by olivier-gerard** [epezent/implot#505]
Hi,

I noted the first and last labels of a colorbar are cropped (see picture below), which gives a bad impression while all the rest is just great.

I suggest following change, making the colormap slightly smaller so labels can fit:
in implot.cpp, void ColormapScale(...)

remove :
```
ImRect bb_grad(bb_frame.Min + gp.Style.PlotPadding + ImVec2(bb_grad_shift, 0),
                   bb_frame.Min + ImVec2(bar_w + gp.Style.PlotPadding.x + bb_grad_shift,
                                         frame_size.y - gp.Style.PlotPadding.y));
```

replaced by:
```
ImRect bb_grad(bb_frame.Min + gp.Style.PlotPadding + ImVec2(bb_grad_shift, label_size.y / 2.f),
                    bb_frame.Min + ImVec2(bar_w + gp.Style.PlotPadding.x + bb_grad_shift,
                                        frame_size.y - gp.Style.PlotPadding.y - label_size.y / 2.f));
```

![image](https://github.com/epezent/implot/assets/88795175/a53b1515-33fe-4099-9c14-743ce68d82fd) -> ![image](https://github.com/epezent/implot/assets/88795175/f37a2eec-7681-49c3-8cc6-f4120c31423e), (or whith white background : ![image](https://github.com/epezent/implot/assets/88795175/56441713-4e4b-46f5-a154-cccd0289abd2) -> ![image](https://github.com/epezent/implot/assets/88795175/bd86043a-be4b-480a-9102-d8f82b22bea4) )

**Comment by epezent** [comment]
Hi, this seems like it might be the result of using a small value for PlotPadding. As you can see, the default values have no issue...

![image](https://github.com/epezent/implot/assets/29577475/944fe194-e8c9-4e96-9b61-c78f0b3cfd5b)

... but making `PlotPadding` (0,0) introduces the clipping:

![image](https://github.com/epezent/implot/assets/29577475/5b697956-d4d2-4ba8-a4a7-105cb1e81e96)

So, you can push and pop a larger value of for PlotPadding around your colorbar to achieve the same result.

**Comment by olivier-gerard** [comment]
Thanks for the hint !
I was pushing a small PlotPadding in order to maximize the colorbar size (and didn't imagine it would affect the labels layout), now I only push it on the X axis and it works nicely.
