### ISSUE TITLE
User Defined Tick Labels

### ISSUE THREAD

**Issue by epezent** [epezent/implot#51]
Both `PlotBars` and `PlotHeatmap` could benefit from the ability to add custom tick labels at specific locations (actually, this is a useful feature in general). The API function(s) for this would likely have to precede`BeginPlot` due to the order in which plot-bounding boxes are calculated. Something like this might work:

```cpp
SetNextPlotTickLabelsX(const char** labels, float* values, int n);
SetNextPlotTickLabelsY(const char** labels, float* values, int n, int y_axis = 0);
```
We would have to consider whether this should add to or override the default tick labels. Thoughts? 

Looping in folks...
@ozlb @sergeyn @jpieper

**Comment by epezent** [comment]
I went ahead and added this. 
https://github.com/epezent/implot/issues/48#issuecomment-638423662

```cpp
// Set the X axis ticks and optionally the labels for the next plot.
void SetNextPlotTicksX(const double* values, int n_ticks, const char** labels = NULL, bool show_default = false);
void SetNextPlotTicksX(double x_min, double x_max, int n_ticks, const char** labels = NULL, bool show_default = false);
// Set the Y axis ticks and optionally the labels for the next plot.
void SetNextPlotTicksY(const double* values, int n_ticks, const char** labels = NULL, bool show_default = false, int y_axis = 0);
void SetNextPlotTicksY(double y_min, double y_max, int n_ticks, const char** labels = NULL, bool show_default = false, int y_axis = 0);
```

Feel free to share feedback. Closing the issue for now.

**Comment by ozlb** [comment]
Neat and great as per your standard, what to say... I like it.
