### ISSUE TITLE
Bug in BenchmarkItem in implot_demo.cpp

### ISSUE THREAD

**Issue by GianUlli** [epezent/implot#62]
There is a memory leak in `BenchmarkItem` in implot_demo.cpp. The `Data` pointer is freed with `delete` even though it points to an array. Please use `delete[]` or switch to a `std::vector` if you can.

This error showed up immediately when running [Cppcheck](http://cppcheck.sourceforge.net) on the code.

**Comment by epezent** [comment]
Thanks, it has been fixed.
