### ISSUE TITLE
bugfix for axes

### ISSUE THREAD

**Issue by itamago** [epezent/implot#76]
Hello,

Small bug when drawing several Begin/EndPlot with different sizes : the axis are based on the canvas BB of the previous Plot.

Quick fix : in implot.cpp move the lines 936-941 ("adaptive division") after the calculation of the canvas BB line 976. Then the axis will use the correct canvas BB (not the previous one)

Thx

**Comment by epezent** [comment]
Thanks for the heads up. I'll get to this eventually. Feel free to submit a PR in the meantime.

**Comment by epezent** [comment]
Fixed! https://github.com/epezent/implot/commit/e847aa786df07ffcc67d88b779b8690f62f300f2
