### ISSUE TITLE
Bounds in heatmap

### ISSUE THREAD

**Issue by plaumiere** [epezent/implot#80]
In heatmap I have observed that another bounds other than [0,1] is not allowing.
After checking the code this issue could be resolved by replacing the max bound set to 1 (for determining the y coordinate of p) by the max y bound as parameter in function RenderHeatmap().

Good job

**Comment by epezent** [comment]
Thanks! It has been resolved, and the demo has been updated to show heatmap bounds in action: https://github.com/epezent/implot/commit/0a3442f389409adb8d04c5f73674f7f50e9bfbd2

```cpp
p.y = bounds_max.y - (0.5*h + r*h);
```

**Comment by 4bb4** [comment]
Wow, that is a quick response. Thanks!

**Comment by 4bb4** [comment]
Oh but wait, this only changes the point plotting code, not the label one - try setting the bounds to (-1,-1) and (1,1), the issue should be reproduced then
