### ISSUE TITLE
Addition of a Fit Data function

### ISSUE THREAD

**Issue by ChiefyChief23** [epezent/implot#83]
I was thinking of adding a function which performs the exact same operation as a double click on a graph to fit the data but as a function call, thoughts? Should be a simple addition (If not already in and I've somehow missed it)

Could also include a new enum to specific which axes you want to fit specifically
```cpp
enum ImPlotAxis_{
X_AXIS,
Y1_AXIS,
Y2_AXIS,
Y3_AXIS,
ALL
}
```

Simple function declaration with default to do all
```cpp
ImPlot::FitData(ImPlotAxis_ axis = ImPlotAxis_::ALL);
```

**Comment by epezent** [comment]
I'm in support of adding a function to manually fit data. Though, I'd rather do it without adding the enum if possible (perhaps 4 bool parameters, all defaulting to `true`?). If that's unavoidable, then I'd want to consider how we could use the enum in other API functions (e.g. those that request a specific y-axis).

**Comment by ChiefyChief23** [comment]
Actually bools would actually be better as then you could select individual axis to fit within one function call. I.e. fit X axis and Y3. 

```cpp
ImPlot::FitData(bool fit_x_axis = true, bool fit_y1_axis = true, bool fit_y2_axis = true, bool fit_y3_axis = true);
```
I've got a crude working version down and tested it. It's a small one but will try and get a merge request in the next day or so as I'm a lil swamped today.

**Comment by epezent** [comment]
Sounds good!
