### ISSUE TITLE
Pie Chart Support

### ISSUE THREAD

**Issue by Togtja** [epezent/implot#9]
My team liked your plotting extension for ImGUI and have integrated it into our project. We are looking for support for pie charts, and we hope this would not be too much work. If you provide some pointers where to start, we could look into doing a pull request.

**Comment by epezent** [comment]
Hi there! Glad your team has found ImPlot useful.

I'm actually working on a pie plotting API already! I should have something working a day or two. However, nothing is finalized yet, so if you have any particular needs or a styling preference, let me know or post pictures.

The API will likely look something like this:

```cpp

char* labels[4]   = {"Dogs","Logs","Frogs","Hogs"};
float percents[4] = {0.45f,  0.10f,  0.15f, 0.30f);
ImVec2 center(0.5f,0.5f); // in plot units, not pixels
float radius = 0.4f;      // in plot units, not pixels

if (BeginPlot("My Pie Chart")) {
    PlotPie(labels, percents, 4, center, radius);
    EndPlot();
}
```

**Comment by epezent** [comment]
![image](https://user-images.githubusercontent.com/29577475/80899347-d0aa5280-8cd4-11ea-8515-99665c56f11e.png)

Basic pie plots have been added. Let me know what you think!

**Comment by carlfindahl** [comment]
This looks nice, I will try it out also! :+1:  Thanks for your work on `implot`

**Comment by Togtja** [comment]
It suits our needs perfectly! Thank you so much for the great work!
